Repository RevenueCat/purchases-android, pull requests merged in 2022-10, with the labels that each got.

#630 Add timeout to Amazon's getProducts and getUserData requests
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/ProductDataHandler.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/UserDataHandler.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt
Labels: fix

#632 Add configuration fragment to purchase tester
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/TesterLogHandler.kt
  examples/purchase-tester/src/main/res/layout/fragment_configure.xml
  examples/purchase-tester/src/main/res/navigation/nav_graph.xml
  examples/purchase-tester/src/main/res/values/colors.xml
  examples/purchase-tester/src/main/res/values/strings.xml
Labels: test

#633 Store purchase tester sdk configuration in DataStore
  examples/purchase-tester/build.gradle
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DataStoreUtils.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SdkConfiguration.kt
Labels: test

#636 Enable HTTP traffic in purchase tester
  examples/purchase-tester/src/main/AndroidManifest.xml
Labels: test

#639 Automate purchase tester publish on releases
  .circleci/config.yml
  Gemfile.lock
  examples/purchase-tester/build.gradle
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/Constants.kt
  fastlane/Fastfile
  fastlane/README.md
  gradle.properties
Labels: test

#643 [AUTOMATIC] Release/5.6.2
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#645 Prepare next version: 5.7.0-SNAPSHOT
  .circleci/config.yml
  .version
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#640 Add cache amazon user data
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/UserDataHandler.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/PurchasingServiceProviderForTest.kt
  test-utils/build.gradle
  test-utils/src/main/java/com/revenuecat/purchases/utils/MockTimestampProvider.kt
  utils/src/main/java/com/revenuecat/purchases/utils/TimestampProvider.kt
Labels: perf

#649 [AUTOMATIC] Release/5.6.3
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#652 Disable unsupported stores in UI
  examples/purchase-tester/build.gradle
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/res/layout/fragment_configure.xml
  examples/purchase-tester/src/main/res/values/strings.xml
  fastlane/Fastfile
  gradle.properties
Labels: test

#651 Prepare next version: 5.7.0-SNAPSHOT
  .circleci/config.yml
  .version
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#654 Remove bc5DevSupport flavor from main
  .circleci/config.yml
  base-application.gradle
  common/build.gradle
  feature/amazon/build.gradle
  feature/google/build.gradle
  library.gradle
  public/build.gradle
  purchases/build.gradle
  test-utils/build.gradle
Labels: refactor

#655 Points latestDependencies to BC5
  base-application.gradle
  common/build.gradle
  feature/google/build.gradle
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/productTypeConversions.kt
  feature/google/src/testLatestDependencies/java/BillingWrapperBC5Test.kt
  library.gradle
  public/build.gradle
  public/src/latestDependencies/java/com/revenuecat/purchases/BillingFeature.kt
  purchases/build.gradle
  test-utils/build.gradle
  test-utils/src/latestDependencies/java/com/revenuecat/purchases/utils/stubsBillingClient5.kt
Labels: breaking, feat

#656 Store debug builds of purchase tester on each commit
  .circleci/config.yml
Labels: ci

#650 Fix GitHub releases not being created
  fastlane/Fastfile
Labels: ci

#644 Moves hold job after integration tests
  .circleci/config.yml
Labels: ci

#659 [BC5 support] Removes all deprecated things
  api-tester/src/main/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  integration-tests/src/androidTest/java/com/revenuecat/purchases/integrationtests/IntegrationTest.kt
  public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/PurchaserInfo.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/GetSkusResponseListener.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/MakePurchaseListener.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/ProductChangeListener.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/PurchaseErrorListener.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/ReceiveCustomerInfoCallback.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/ReceiveOfferingsCallback.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/ReceiveOfferingsListener.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/ReceivePurchaserInfoListener.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/UpdatedPurchaserInfoListener.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/deprecatedListenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetStoreProductsCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/ProductChangeCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/PurchaseCallback.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: breaking, refactor

#662 BC5 purchase flow new API
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/unityIAP/java/com/revenuecat/purchases/google/BillingWrapper.kt
  public/src/latestDependencies/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/StoreProductExtensions.kt
Labels: feat

#664 [BC5] QueryProductDetails
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PackageAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/pricingPhaseConversions.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/BillingWrapperCommonTest.kt
  feature/google/src/unityIAP/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/unityIAP/java/com/revenuecat/purchases/google/storeProductConversions.kt
  public/src/latestDependencies/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/Package.kt
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/RecurrenceMode.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/parceler/JSONObjectParceler.kt
  public/src/unityIAP/java/com/revenuecat/purchases/GoogleStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat
