Repository RevenueCat/purchases-android, pull requests merged in 2022-08, with the labels that each got.

#567 Remove billing client 3 support
  api-tester/build.gradle
  build.gradle
  common/build.gradle
  common/src/main/java/com/revenuecat/purchases/common/purchaseExtensions.kt
  common/src/main/java/com/revenuecat/purchases/common/purchaseHistoryRecordExtensions.kt
  common/src/unityIAP/java/com/revenuecat/purchases/common/purchaseExtensionsBillingClient3.kt
  common/src/unityIAP/java/com/revenuecat/purchases/common/purchaseHistoryRecordExtensionsBillingClient3.kt
  config/detekt/detekt-baseline.xml
  feature/google/build.gradle
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/BillingResponseCodeTest.kt
  feature/google/src/test/java/BillingWrapperTest.kt
  feature/google/src/test/java/ParcelableTests.kt
  feature/google/src/unityIAP/java/com/revenuecat/purchases/google/BillingFlowParamsExtensionsBillingClient3.kt
  integration-tests/build.gradle
  public/build.gradle
  purchases/build.gradle
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  test-utils/build.gradle
  test-utils/src/main/java/com/revenuecat/purchases/utils/stubsBillingClient4.kt
  test-utils/src/unityIAP/java/com/revenuecat/purchases/utils/stubsBillingClient3.kt
Labels: HOLD

#589 Release/5.5.0
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#590 Prepare next version: 5.6.0-SNAPSHOT
  .circleci/config.yml
  .version
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#592 Rename package name of purchase tester app to com.revenuecat.purchases_sample
  examples/purchase-tester/build.gradle
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LoginFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainActivity.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
Labels: build, refactor

#593 CleverTapID integration
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: enhancement

#600 Update releasing documentation
  RELEASING.md
Labels: docs

#597 Adds Danger
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: ci

#599 Release train
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#596 Release/5.6.0
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#598 Prepare next version: 5.7.0-SNAPSHOT
  .circleci/config.yml
  .version
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release
