Repository RevenueCat/purchases-android, pull requests merged in 2022-09, with the labels that each got.

#608 Create flavor folders for api testers
  api-tester/src/bc5SupportDev/java/com/revenuecat/apitester/java/PurchasesBC5API.java
  api-tester/src/bc5SupportDev/java/com/revenuecat/apitester/kotlin/PurchasesBC5API.kt
  api-tester/src/latestDependencies/java/com/revenuecat/apitester/java/PurchasesBC4API.java
  api-tester/src/latestDependencies/java/com/revenuecat/apitester/kotlin/PurchasesBC4API.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
Labels: refactor

#604 Wait to obtain unsubscribed attributes until finishing getting device identifiers
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: fix

#606 SkuType -> ProductType Updates
  .circleci/config.yml
  api-tester/build.gradle
  api-tester/src/bc5SupportDev/java/com/revenuecat/apitester/java/PurchasesBC5API.java
  api-tester/src/bc5SupportDev/java/com/revenuecat/apitester/kotlin/PurchasesBC5API.kt
  api-tester/src/latestDependencies/java/com/revenuecat/apitester/java/PurchasesBC4API.java
  api-tester/src/latestDependencies/java/com/revenuecat/apitester/kotlin/PurchasesBC4API.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  base-application.gradle
  config/detekt/detekt-baseline.xml
  fastlane/Fastfile
  feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
  feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/productTypeConversions.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/latestDependencies/java/com/revenuecat/purchases/google/productTypeConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/testBc5SupportDev/java/BillingWrapperTest.kt
  feature/google/src/testLatestDependencies/java/BillingWrapperTest.kt
  library.gradle
  public/src/bc5SupportDev/java/com/revenuecat/purchases/BillingFeature.kt
  public/src/latestDependencies/java/com/revenuecat/purchases/BillingFeature.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/src/bc5SupportDev/java/com/revenuecat/purchases/utils/stubsBillingClient5.kt
  test-utils/src/latestDependencies/java/com/revenuecat/purchases/utils/stubsBillingClient4.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/SkuDetailsStub.kt
Labels: refactor

#611 Move to SNAPSHOT version on every commit to main if needed
  .circleci/config.yml
  Gemfile.lock
Labels: ci

#612 [AUTOMATIC] Release/5.6.1
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#614 Prepare next version: 5.7.0-SNAPSHOT
  .circleci/config.yml
  .version
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#602 Update releasing instructions
  RELEASING.md
Labels: docs

#618 Add package name to all requests headers
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt
Labels: feat

#620 Add missing packageName to helper methods in AppConfig
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  common/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
Labels: refactor

#617 BillingWrapperTests refactor
  feature/google/src/test/java/BillingWrapperCommonTest.kt
  feature/google/src/test/java/BillingWrapperTestBase.kt
  feature/google/src/testBc5SupportDev/java/BillingWrapperBC5Test.kt
  feature/google/src/testBc5SupportDev/java/BillingWrapperTest.kt
  feature/google/src/testUnityIAP/java/BillingWrapperBC4Test.kt
  test-utils/build.gradle
  test-utils/src/bc5SupportDev/java/com/revenuecat/purchases/utils/stubsBillingClient5.kt
  test-utils/src/unityIAP/java/com/revenuecat/purchases/utils/stubsBillingClient4.kt
Labels: refactor, test

#624 Not create release if next version should be skipped
  fastlane/Fastfile
Labels: ci

#621 Adds action parameter to CircleCI config to be able to trigger the automatic bump manually
  .circleci/config.yml
  RELEASING.md
Labels: ci

#616 Initial Support for BillingClient5
  .circleci/config.yml
  api-tester/build.gradle
  api-tester/src/bc5SupportDev/java/com/revenuecat/apitester/java/PurchasesBC5API.java
  api-tester/src/bc5SupportDev/java/com/revenuecat/apitester/kotlin/PurchasesBC5API.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/unityIAP/java/com/revenuecat/apitester/java/PurchasesBC4API.java
  api-tester/src/unityIAP/java/com/revenuecat/apitester/kotlin/PurchasesBC4API.kt
  base-application.gradle
  build.gradle
  common/build.gradle
  config/detekt/detekt-baseline.xml
  fastlane/Fastfile
  feature/amazon/build.gradle
  feature/google/build.gradle
  feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
  feature/google/src/bc5SupportDev/java/com/revenuecat/purchases/google/productTypeConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/BillingWrapperCommonTest.kt
  feature/google/src/test/java/BillingWrapperTestBase.kt
  feature/google/src/testBc5SupportDev/java/BillingWrapperBC5Test.kt
  feature/google/src/testUnityIAP/java/BillingWrapperBC4Test.kt
  feature/google/src/unityIAP/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/unityIAP/java/com/revenuecat/purchases/google/productTypeConversions.kt
  integration-tests/build.gradle
  library.gradle
  public/build.gradle
  public/src/bc5SupportDev/java/com/revenuecat/purchases/BillingFeature.kt
  public/src/unityIAP/java/com/revenuecat/purchases/BillingFeature.kt
  purchases/build.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/build.gradle
  test-utils/src/bc5SupportDev/java/com/revenuecat/purchases/utils/stubsBillingClient5.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/SkuDetailsStub.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/stubsBillingClient4.kt
  test-utils/src/unityIAP/java/com/revenuecat/purchases/utils/stubsBillingClient4.kt
Labels: dependencies, refactor

#626 Offerings cleanup
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  public/src/main/java/com/revenuecat/purchases/Package.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor
