Repository RevenueCat/purchases-android, pull requests merged in 2022-12, with the labels that each got.

#700 [BC5] Fix missing plan identifier in JSON response
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: fix

#702 Backend test cleanup
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: refactor, test

#701 Disable unsupported features for first BC5 beta
  purchases/src/main/kotlin/com/revenuecat/purchases/FeatureLockUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: feat

#703 Refactor postReceipt helper method
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: refactor, test

#704 Fix API Testers
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
Labels: fix

#707 fix build errors and add postReceipt PostingTransactionsTests
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: test

#709 [BC5] Update v6-MIGRATION.md
  migrations/v6-MIGRATION.md
Labels: docs

#706 Clean up PurchasesTest
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor

#712 Fix PurchasesTest, BillingWrapperTest and comments out Amazon tests
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: test

#714 Added androidx.lifecycle.DefaultLifecycleObserver to consumer-rules.pro
  purchases/consumer-rules.pro
Labels: fix

#713 [BC5] Change purchasing API with latest changes
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: breaking, refactor

#716 [BC5] Expose default purchase option store product
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/StoreProductExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: feat

#711 Fix PostingTransactionsTests
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
Labels: test

#708 BackendTests and BillingWrapperTests for postReceipt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: test

#720 [CF-1065] Fix and add tests for listing of INAPP StoreProducts
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
Labels: fix

#721 [CF-1000] Sends up price and currency for inapps
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/FeatureLockUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: fix

#724 Update fastlane-plugin-revenuecat_internal to latest version
  Gemfile.lock
Labels: ci
