Repository RevenueCat/purchases-android, pull requests merged in 2022-11, with the labels that each got.

#661 [BC5] Offerings creation
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: feat

#668 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#670 Use mocks for BC5 purchase classes since constructor is not public anymore
  feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: test

#671 Fix existing BillingWrapper unit tests related to purchasing
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: test

#673 Bc5 add new listener helper methods
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#672 BC5 Continue fixing purchase tests and add missing BillingWrapper tests
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: test

#674 [BC5] Fix OfferingsTests
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: test

#675 [BC5] Fix QueryProductDetails tests
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/queryProductDetailsParamsExtensions.kt
Labels: test

#677 BC5 purchase-tester and StoreTransaction updates
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/purchaseExtensions.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ReceiptToStoreTransactionTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt
Labels: enhancement, breaking, feat

#680 Replace StoreProduct.sku with productId
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: enhancement, breaking, feat

#681 Update Fastlane plugin
  Gemfile.lock
Labels: ci

#686 [BC5] Update dependency to BC 5.1.0
  build.gradle
Labels: dependencies

#683 [BC5] Creates v6-MIGRATION.md
  migrations/v6-MIGRATION.md
Labels: docs

#684 [BC5] Support PurchaseOptions in purchase tester app
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PurchaseOptionExtensions.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  examples/purchase-tester/src/main/res/values/strings.xml
Labels: enhancement, test

#687 Fix for calling getUnsyncedSubscriberAttributes callback twice
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
Labels: fix

#691 Remove unnecessary appcompat dependency
  feature/identity/build.gradle
  feature/subscriber-attributes/build.gradle
Labels: dependencies

#693 Bump version
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
Labels: next_release

#690 [BC5] Map packages to SubscriptionOfferDetails using basePlanId instead of duration
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
  public/src/main/java/com/revenuecat/purchases/Package.kt
  public/src/main/java/com/revenuecat/purchases/models/GooglePurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: feat

#699 [BC5] Fix offerings
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#694 [BC5] Fix detekt issues
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchaseOptionApi.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/purchaseExtensions.kt
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  public/src/main/java/com/revenuecat/purchases/Package.kt
  public/src/main/java/com/revenuecat/purchases/models/GooglePurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
  utils/src/main/java/com/revenuecat/purchases/utils/Result.kt
Labels: style

#698 [CF-971] BC5 postReceipt updates
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesState.kt
Labels: enhancement, refactor
