Repository RevenueCat/purchases-android, pull requests merged in 2023-02, with the labels that each got.

#765 Update gems
  Gemfile.lock
Labels: dependencies

#770 [BC5] Add `storeProduct` to `ReceiptInfo`'s equals method (and fix broken tests because of this)
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#772 [BC5] Merge changes from 5.7.0
  .circleci/config.yml
  .github/stale.yml
  .version
  CHANGELOG.md
  Gemfile.lock
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  build.gradle
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/logUtils.kt
  common/src/main/java/com/revenuecat/purchases/common/logWrapper.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/LogHandlerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/LogUtilsTest.kt
  examples/MagicWeather/README.md
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LogLevel.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LogMessage.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/TesterLogHandler.kt
  fastlane/Pluginfile
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  library.gradle
  public/src/main/java/com/revenuecat/purchases/LogHandler.kt
  public/src/main/java/com/revenuecat/purchases/LogLevel.kt
  public/src/test/java/com/revenuecat/purchases/LogLevelTest.kt
  purchases/consumer-rules.pro
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesLoggerTest.kt
Labels: fix

#774 Revert "Update gems"
  Gemfile.lock
  fastlane/Pluginfile
Labels: fix

#775 Bc5 support merge 5.7 main again
  CHANGELOG.md
  Gemfile.lock
Labels: fix

#776 Release/6.0.0-alpha.3
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#763 Updating comment for syncPurchases
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: docs

#769 Adds dependabot
  .github/dependabot.yml
  Gemfile
Labels: ci

#768 [CF-1121] Update Magic Weather for BC5 / SDK V6
  examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallAdapter.kt
  examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallFragment.kt
  examples/MagicWeather/app/src/main/res/layout/paywall_item.xml
  examples/MagicWeather/build.gradle
Labels: refactor

#788 Add queries
  examples/purchase-tester/src/main/AndroidManifest.xml
Labels: bug

#732 Fix callback error issue
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#784 Diagnostics: Add jsonl file management for diagnostics
  common/src/main/java/com/revenuecat/purchases/common/FileHelper.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
  common/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
Labels: refactor

#797 [BC5] Fix value of NON_RECURRING from 0 to 3
  public/src/main/java/com/revenuecat/purchases/models/RecurrenceMode.kt
  public/src/test/java/com/revenuecat/purchases/RecurrenceModeTest.kt
Labels: fix

#791 Diagnostics: Sync diagnostics when configuring SDK if needed
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: feat

#794 [BC5] Price API improvements
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/findDefaultOffer.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/pricingPhaseConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/SubscriptionOptionTest.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/Price.kt
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: feat

#795 Diagnostics: Diagnostics split manager into tracker and synchronizer
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#803 Diagnostics: Track endpoint hit
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsLogEventName.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  common/src/main/java/com/revenuecat/purchases/common/durationExtensions.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/HTTPResult.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBackend.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
Labels: feat

#804 Diagnostics: Increase jittering for diagnostics backend calls
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/Dispatcher.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/SyncDispatcher.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/SyncDispatcher.kt
Labels: refactor

#805 Diagnostics: Adapt to latest backend changes
  common/src/main/java/com/revenuecat/purchases/common/FileHelper.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventName.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  common/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
Labels: refactor

#815 [BC5] update StoreProduct title doc for Google base plans not having a title
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
Labels: docs

#814 [BC5] Maps StoreProducts on basePlanId and not duration (fixes issue with prepaid with same duration as recurring)
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
Labels: fix

#813 [BC5] Fixes logMissingProducts never logging missing products
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: fix

#806 [BC5] New Period and Unit classes to represent ISO8601 period strings
  .sdkmanrc
  api-tester/src/main/java/com/revenuecat/apitester/java/PeriodAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PeriodAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/findDefaultOffer.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/pricingPhaseConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/FindBestOfferTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/SubscriptionOptionTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/Period.kt
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: feat

#818 Fix period serialization
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
Labels: bug

#781 Remove `tag_release_with_latest_if_needed` fastlane lane
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#786 Update README.md to include minimum Kotlin version
  README.md
Labels: docs
