Repository RevenueCat/purchases-android, pull requests merged in 2023-03, with the labels that each got.

#827 Fix bundle install on CircleCI
  .circleci/config.yml
Labels: ci

#816 [BC5] New SubscriptionOptions model
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionsAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionsAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/findDefaultOffer.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/FindBestOfferTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
  public/src/test/java/com/revenuecat/purchases/common/models/SubscriptionOptionsTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: refactor

#829 [BC5] Migration guide updates for API improvements
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
Labels: docs

#809 Fix issue with missing subscriber attributes if set after login but before login callback
  config/detekt/detekt-baseline.xml
  feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesCache.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesDeviceCacheTests.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
  strings/src/main/java/com/revenuecat/purchases/strings/AttributionStrings.kt
Labels: fix

#836 Fix docs deployment
  .circleci/config.yml
Labels: fix

#820 Entitlement verification: Architecture and API
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementVerificationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesErrorAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementVerificationModeAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesErrorAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/Dispatcher.kt
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/errors.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/HTTPRequest.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/HTTPResult.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationException.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerifier.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/entitlementVerificationModeExtensions.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPResultMockFactory.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementVerificationMode.kt
  public/src/main/java/com/revenuecat/purchases/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  strings/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt
Labels: feat

#823 Entitlement verification: Add Tink dependency to perform signature verification
  build.gradle
  common/build.gradle
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerifier.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/DefaultSignatureVerifierTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
Labels: feat

#826 Entitlement verification: Refactor SigningManager to make it not-nullable
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/entitlementVerificationModeExtensions.kt
  common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  strings/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt
Labels: refactor

#830 Entitlement verification: Add entitlement verification options to purchase tester
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/res/drawable/spinner_bg.xml
  examples/purchase-tester/src/main/res/layout/fragment_configure.xml
  examples/purchase-tester/src/main/res/values/dimens.xml
  examples/purchase-tester/src/main/res/values/strings.xml
Labels: test

#831 Entitlement verification: Avoid caching responses with verification errors
  common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPResultMockFactory.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
Labels: fix

#822 Fix SDKMAN issues
  .circleci/config.yml
Labels: build

#834 [BC5] Update MagicWeather and Purchase Tester with 6.0.0-alpha.4 APIs
  examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallAdapter.kt
  examples/MagicWeather/build.gradle
Labels: refactor

#825 Purchase.Builder
  api-tester/src/main/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesState.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/ProductChangeCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/PurchaseCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
Labels: breaking, feat

#838 Entitlement verification: Rename not verified to not requested and error to failed
  api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/HTTPResult.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPResultMockFactory.kt
  common/src/test/java/com/revenuecat/purchases/common/MockCustomerInfoFactory.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
  public/src/main/java/com/revenuecat/purchases/VerificationResult.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#842 Entitlement verification: Return current call verification result over cached version
  common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
Labels: fix

#847 [BC5] Always use purchasingData property directly on the StoreProduct when purchasing
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
Labels: refactor

#840 Entitlement verification: Not perform verification if request returns error
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
Labels: fix

#851 Grant grace period for entitlements when the backend is offline
  common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  common/src/test/java/com/revenuecat/purchases/common/testDurationExtensions.kt
  public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/Responses.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/dateExtensions.kt
  utils/src/main/java/com/revenuecat/purchases/utils/DateHelper.kt
Labels: refactor

#839 Entitlement verification: Fix request verification
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
Labels: fix

#850 Purchase.Builder Follow-up
  api-tester/src/main/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedOfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedPackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/res/navigation/nav_graph.xml
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesState.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/ProductChangeCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/PurchaseCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchaseParamsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: breaking

#849 [BC5] Add/use productPlanIdentifier to EntitlementInfo and CustomerInfo
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/Responses.kt
  utils/src/main/java/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
Labels: feat

#843 [BC5] New API for getting products by type, properly filter deprecated functions, reworked logic
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#857 Fix issue posting receipts to backend
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
Labels: fix

#858 Hide isPersonalizedPrice
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
Labels: refactor

#860 Release/6.0.0-beta.1
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#862 Update CHANGELOG with improved notes about SDK issue
  CHANGELOG.latest.md
  CHANGELOG.md
Labels: docs

#864 Pass isPersonalizedPrice through to purchases
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#867 Release/6.0.0-beta.2
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#854 Fix docs deployment paths
  .circleci/config.yml
Labels: refactor

#856 Entitlement verification: Send updated value in listener when verification result changes
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
Labels: refactor

#866 Remove Parcelable implementation for classes with ProductDetails as a member
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/Offering.kt
  public/src/main/java/com/revenuecat/purchases/Offerings.kt
  public/src/main/java/com/revenuecat/purchases/Package.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: breaking

#868 Log message when trying configure the SDK multiple times
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt
Labels: refactor

#869 Improve tests on etag cache verification logic
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
Labels: test

#872 Update VerificationResult NOT_REQUESTED docs to new behavior
  public/src/main/java/com/revenuecat/purchases/VerificationResult.kt
Labels: docs

#870 Improve entitlement verification documentation
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
Labels: docs

#874 Rename verification result SUCCESS to VERIFIED
  api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/HTTPResultTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  public/src/main/java/com/revenuecat/purchases/VerificationResult.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
Labels: refactor

#880 Add verification result to purchase tester overview page
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
Labels: test

#879 [BC5] Re-add `price_string` header on postReceipt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
Labels: fix

#824 Amazon Offering Parsing
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingParser.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonOfferingParser.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonOfferingsTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/GoogleOfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/OfferingParserFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#883 [BC5] Cleaning up some TODOs in the code
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedOfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: refactor

#882 [BC5] Make Activity first param in PurchaseParams
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchaseParamsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor

#887 Fix flaky test in EntitlementInfoTest
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
Labels: test

#881 [BC5] AmazonStoreProduct updates
  api-tester/build.gradle
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  examples/purchase-tester/build.gradle
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedPackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  fastlane/Fastfile
  fastlane/README.md
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonPurchasingData.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStoreProduct.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonOfferingsTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/PriceExtractorTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt
  gradle.properties
  purchases/src/main/kotlin/com/revenuecat/purchases/FeatureLockUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: breaking

#889 [BC5] Use `rc-ignore-offer` instead of `rc-ignore-befault-offer`
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: breaking

#890 [BC5] Rename `introTrial` to `introOffer` on `SubscriptionOptions`
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionsAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionsAPI.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOptions.kt
  public/src/test/java/com/revenuecat/purchases/common/models/SubscriptionOptionsTest.kt
Labels: breaking

#886 Hide all new Trusted entitlements APIs
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfosAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementVerificationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesErrorAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfosAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementVerificationModeAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesErrorAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/errors.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementVerificationMode.kt
  public/src/main/java/com/revenuecat/purchases/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  utils/src/main/java/com/revenuecat/purchases/VerificationResult.kt
Labels: refactor

#888 Offline entitlements: Created `ProductEntitlementMapping`
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMappings.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMappingsTest.kt
Labels: refactor

#878 [BC5] Re-enable `observerMode` and `syncPurchases()`
  purchases/src/main/kotlin/com/revenuecat/purchases/FeatureLockUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: feat

#895 Release/6.0.0-beta.3
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#891 Offline entitlements: Add support for fetching ProductEntitlement mappings
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
Labels: refactor

#894 Support requests without ETags
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
Labels: refactor

#900 Revert "Support requests without ETags (#894)"
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
Labels: refactor

#893 Offline entitlements: Add `OfflineEntitlementsManager` and add operation to perform backend request and cache result in device
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor

#897 Offline entitlements: Rename `ProductEntitlementMappings` -> `ProductEntitlementMapping`
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMapping.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMappingTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/productEntitlementMappingFactory.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor

#899 Add integration tests that can mock the Store
  .run/Integration Tests.run.xml
  .run/Purchases Integration Tests (set purchases module variant before executing).run.xml
  build.gradle
  purchases/build.gradle
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreProductFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/integrationTest/AndroidManifest.xml
  purchases/src/integrationTest/kotlin/com/revenuecat/purchases/MainActivity.kt
  purchases/src/integrationTest/res/mipmap-hdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-hdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-mdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-mdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xxhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xxhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xxxhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xxxhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/values-night/themes.xml
  purchases/src/integrationTest/res/values/colors.xml
  purchases/src/integrationTest/res/values/strings.xml
  purchases/src/integrationTest/res/values/themes.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
Labels: test

#902 PurchaseTester gets observable mode for google
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ObserverModeBillingClient.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/res/layout/fragment_configure.xml
Labels: refactor

#903 Make personalized price checkbox
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
Labels: fix

#906 [BC5] Fix entitlment info to string plan identifier
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
Labels: fix

#907 [BC5] Small improvements to v6-MIGRATION.md
  migrations/v6-MIGRATION.md
Labels: docs

#877 Improve diagnostics counters system by adding anonymization and changing counter name to an enum
  common/src/main/java/com/revenuecat/purchases/common/Anonymizer.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsCounterName.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  common/src/test/java/com/revenuecat/purchases/common/AnonymizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
Labels: refactor

#901 Automate purchases module integration tests
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
  purchases/.gitignore
  purchases/build.gradle
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreProductFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
  purchases/src/integrationTest/AndroidManifest.xml
Labels: test

#896 Offline entitlements: Initialize OfflineEntitlementsManager and perform cache update on SDK configuration
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#916 Removes strict mode from purchase tester
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
Labels: fix

#917 Fix tests after PR merge changes
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: test

#912 Refactors BillingAbstract to not depend on Backend
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/BackendHelper.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBackend.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  integration-tests/build.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt
Labels: refactor

#914 Adds multidex to integration tests
  integration-tests/build.gradle
  integration-tests/src/main/AndroidManifest.xml
Labels: build

#908 Filter out expired purchases from queryPurchases in Amazon store
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt
Labels: refactor

#911 Automate integration tests for load shedder
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: build, test

#918 [BC5] Add `platform_product_ids` to post receipt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/SubscriptionOptionTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
  public/src/test/java/com/revenuecat/purchases/common/models/SubscriptionOptionsTest.kt
Labels: feat

#910 Release/6.0.0-rc.1
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#919 [CF-1296] v6 Migration updates and Entitlement/CustomerInfo docs on productIds
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
Labels: docs

#924 Release/6.0.0
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
  migrations/v6-MIGRATION.md
Labels: next_release

#926 Fix infinite loop when accesing deprecated property
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
Labels: fix

#927 Release/6.0.1
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#928 Re-add new integration tests after V6 changes
  .circleci/config.yml
  base-application.gradle
  fastlane/Fastfile
  feature/amazon/build.gradle
  gradle.properties
  library.gradle
  purchases/build.gradle
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreProductFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/integrationTest/AndroidManifest.xml
  purchases/src/integrationTest/res/values-night/themes.xml
  purchases/src/integrationTest/res/values/themes.xml
Labels: test
