Repository RevenueCat/purchases-android, pull requests merged in 2023-06, with the labels that each got.

#1037 [EXTERNAL] Update Kover to 0.7.0 (#1031) via @mikescamell
  .circleci/config.yml
  build.gradle
  library.gradle
  purchases/build.gradle
Labels: dependencies

#1034 [PurchaseTester] Update CustomerInfo from listener in overview screen
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
Labels: test

#1043 [EXTERNAL] Add `MagicWeather` app note to the main `README` and fix a typo (#1041)
  README.md
Labels: docs

#1044 [EXTERNAL] Replace `@Deprecated` usage of `skus` by `productIds` from`PurchasedProductsFetcher` (#986) via @pablo-guardiola
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
Labels: refactor, test

#1049 Update gradle plugin to 8.0.2
  build.gradle
  examples/MagicWeather/build.gradle
Labels: dependencies

#1053 Fix backend integration test flakiness
  fastlane/Fastfile
Labels: test

#1012 Add Coroutine support to Purchases#getCustomerInfo
  .idea/codeStyles/Project.xml
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesExceptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesExceptionAPI.kt
  build.gradle
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  purchases/build.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesException.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesExceptionTest.kt
Labels: feat

#1062 Update to latest android executor image
  .circleci/config.yml
Labels: build

#1065 [EXTERNAL] Add `ExperimentalPreviewRevenueCatPurchasesAPI` opt-in requirement to `Purchases.awaitCustomerInfo()` (#1060)
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  public/src/main/java/com/revenuecat/purchases/ExperimentalPreviewRevenueCatPurchasesAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
Labels: refactor

#1061 Make enabling entitlement verification also enabled diagnostics
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
Labels: refactor

#1066 Require experimental annotation for trusted entitlements API
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfosAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
Labels: refactor

#1048 Trusted entitlements
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfosAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementVerificationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesErrorAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfosAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementVerificationModeAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesErrorAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/errors.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfos.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementVerificationMode.kt
  public/src/main/java/com/revenuecat/purchases/VerificationResult.kt
  public/src/main/java/com/revenuecat/purchases/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
Labels: feat

#1072 Return error in queryPurchases if error connecting to billing client
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: fix

#1070 Trusted entitlements: Add internal mechanism to force signing errors for tests
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
  common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
Labels: test

#1071 Trusted entitlements: Add integration tests
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt
Labels: test

#1052 Refactor CustomerInfo listener and cache logic into CustomerInfoUpdater
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoUpdateHandler.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoUpdateHandlerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#1058 Refactor syncing pending transactions logic out of `Purchases`
  purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostTransactionWithProductDetailsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
Labels: refactor

#1073 Sync pending purchases before getting customer info
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/CustomerInfoStrings.kt
Labels: refactor

#1076 Handle other diagnostics-related exceptions
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
Labels: fix

#1067 Trusted entitlements: Add logs with verification mode
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  strings/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt
Labels: refactor

#1059 Migrate to Gradle version catalog
  api-tester/build.gradle
  base-application.gradle
  build.gradle
  common/build.gradle
  examples/MagicWeather/app/build.gradle
  examples/MagicWeather/build.gradle
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeather/settings.gradle
  examples/purchase-tester/build.gradle
  feature/amazon/build.gradle
  feature/google/build.gradle
  feature/identity/build.gradle
  feature/subscriber-attributes/build.gradle
  gradle/libs.versions.toml
  integration-tests/build.gradle
  library.gradle
  public/build.gradle
  purchases/build.gradle
  settings.gradle
  strings/build.gradle
  test-utils/build.gradle
  utils/build.gradle
Labels: build

#1080 Default customer info schema version to latest known by SDK
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  common/src/test/java/com/revenuecat/purchases/common/CustomerInfoFactoryTest.kt
Labels: fix

#1082 Compose sample app: automate builds
  .circleci/config.yml
  fastlane/Fastfile
Labels: test

#1074 Add defaultsRelease variant tests run configuration
  .run/Debug tests.run.xml
  .run/Release tests.run.xml
Labels: build

#1085 Fix offline entitlements integration tests
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsFreshInstallIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
Labels: test

#1092 Update billing library to 5.2.1
  gradle/libs.versions.toml
Labels: dependencies

#1100 Update CHANGELOG.md to include external contribution
  CHANGELOG.md
Labels: docs

#1097 Remove strings module
  common/build.gradle
  common/src/main/java/com/revenuecat/purchases/strings/AttributionStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/BillingStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/ConfigureStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/CustomerInfoStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/Emojis.kt
  common/src/main/java/com/revenuecat/purchases/strings/IdentityStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/ReceiptStrings.kt
  common/src/main/java/com/revenuecat/purchases/strings/RestoreStrings.kt
  feature/amazon/build.gradle
  feature/google/build.gradle
  feature/identity/build.gradle
  feature/subscriber-attributes/build.gradle
  public/build.gradle
  purchases/build.gradle
  settings.gradle
  strings/.gitignore
  strings/build.gradle
  strings/gradle.properties
  strings/src/main/AndroidManifest.xml
Labels: refactor

#1098 Delete utils module
  common/build.gradle
  common/src/main/java/com/revenuecat/purchases/utils/DateHelper.kt
  common/src/main/java/com/revenuecat/purchases/utils/Iso8601Utils.java
  common/src/main/java/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
  common/src/main/java/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
  common/src/main/java/com/revenuecat/purchases/utils/MapExtensions.kt
  common/src/main/java/com/revenuecat/purchases/utils/Result.kt
  common/src/main/java/com/revenuecat/purchases/utils/TimestampProvider.kt
  config/detekt/detekt-baseline.xml
  feature/amazon/build.gradle
  feature/google/build.gradle
  feature/identity/build.gradle
  feature/subscriber-attributes/build.gradle
  public/build.gradle
  public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
  public/src/main/java/com/revenuecat/purchases/utils/DateHelperDupe.kt
  public/src/main/java/com/revenuecat/purchases/utils/Iso8601UtilsDupe.kt
  public/src/main/java/com/revenuecat/purchases/utils/JSONArrayExtensionsDupe.kt
  public/src/main/java/com/revenuecat/purchases/utils/JSONObjectExtensionsDupe.kt
  public/src/main/java/com/revenuecat/purchases/utils/JSONObjectParceler.kt
  public/src/main/java/com/revenuecat/purchases/utils/SerializationException.kt
  public/src/test/java/com/revenuecat/purchases/common/models/TransactionTest.kt
  public/src/test/java/com/revenuecat/purchases/utils/JSONArrayExtensionsTest.kt
  public/src/test/java/com/revenuecat/purchases/utils/JSONObjectExtensionsTest.kt
  purchases/build.gradle
  settings.gradle
  test-utils/build.gradle
  utils/.gitignore
  utils/build.gradle
  utils/consumer-rules.pro
  utils/gradle.properties
  utils/proguard-rules.pro
  utils/src/main/AndroidManifest.xml
Labels: refactor

#1102 Remove subscriber attributes module
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttribute.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/backendHelpers.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesCache.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesMigrationExtensions.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/caching/cachingHelpers.kt
  common/src/main/java/com/revenuecat/purchases/subscriberattributes/subscriberAttributesFactories.kt
  common/src/test/java/com/revenuecat/purchases/subscriberattributes/SpecialSubscriberAttributesTests.kt
  common/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributeTests.kt
  common/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  common/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesDeviceCacheTests.kt
  common/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
  feature/identity/build.gradle
  feature/subscriber-attributes/.gitignore
  feature/subscriber-attributes/build.gradle
  feature/subscriber-attributes/consumer-rules.pro
  feature/subscriber-attributes/gradle.properties
  feature/subscriber-attributes/proguard-rules.pro
  feature/subscriber-attributes/src/main/AndroidManifest.xml
  purchases/build.gradle
  settings.gradle
Labels: refactor

#1104 Remove feature:google module
  common/build.gradle
  common/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
  common/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  common/src/main/java/com/revenuecat/purchases/google/PurchaseContext.kt
  common/src/main/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcher.kt
  common/src/main/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
  common/src/main/java/com/revenuecat/purchases/google/billingResultExtensions.kt
  common/src/main/java/com/revenuecat/purchases/google/errors.kt
  common/src/main/java/com/revenuecat/purchases/google/pricingPhaseConversions.kt
  common/src/main/java/com/revenuecat/purchases/google/productTypeConversions.kt
  common/src/main/java/com/revenuecat/purchases/google/purchaseStateConversions.kt
  common/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  common/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  common/src/main/java/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
  common/src/test/java/com/revenuecat/purchases/google/BillingResponseCodeTest.kt
  common/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  common/src/test/java/com/revenuecat/purchases/google/ParcelableTests.kt
  common/src/test/java/com/revenuecat/purchases/google/StoreProductConversionsTest.kt
  common/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  common/src/test/java/com/revenuecat/purchases/google/SubscriptionOptionTest.kt
  common/src/test/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcherTests.kt
  feature/google/.gitignore
  feature/google/build.gradle
  feature/google/consumer-rules.pro
  feature/google/gradle.properties
  feature/google/proguard-rules.pro
  feature/google/src/main/AndroidManifest.xml
  purchases/build.gradle
  settings.gradle
  test-utils/build.gradle
Labels: refactor

#1107 [EXTERNAL] Add `awaitCustomerInfo` / coroutines tests to `TrustedEntitlementsInformationalModeIntegrationTest` (#1077) via @pablo-guardiola
  gradle/libs.versions.toml
  purchases/build.gradle
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt
Labels: test

#1109 Trusted entitlements: Add Signature type to process new signature response format
  common/src/main/java/com/revenuecat/purchases/common/verification/Signature.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SignatureTest.kt
Labels: refactor

#1110 Trusted entitlements: Add IntermediateSignatureHelper to handle intermediate signature verification process
  common/src/main/java/com/revenuecat/purchases/common/IntExtensions.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/IntermediateSignatureHelper.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerifier.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/IntermediateSignatureHelperTest.kt
Labels: refactor

#1112 Move amazon module into purchases
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  feature/amazon/build.gradle
  feature/amazon/src/main/AndroidManifest.xml
  purchases/build.gradle
  purchases/src/main/AndroidManifest.xml
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonBackend.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonCache.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonOfferingParser.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonPurchasingData.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonStoreProduct.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/AmazonStrings.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/DefaultPurchasingServiceProvider.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/ISO3166Alpha2ToISO42170Converter.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/PurchasingServiceProvider.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/attribution/AmazonDeviceIdentifiersFetcher.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/errors.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/handler/ProductDataHandler.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandler.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/handler/UserDataHandler.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/listener/ProductDataResponseListener.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/listener/PurchaseResponseListener.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/listener/PurchaseUpdatesResponseListener.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/listener/UserDataResponseListener.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/productTypeConversions.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingActivity.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingActivityBroadcastReceiver.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingDelegate.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  purchases/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/res/values-v21/styles.xml
  purchases/src/main/res/values/styles.xml
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonCacheTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonOfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/PriceExtractorTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/ProductConverterTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/ReceiptToStoreTransactionTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/StoreProductTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/attribution/AmazonDeviceIdentifiersFetcherTests.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandlerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/helpers/MockDeviceCache.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/helpers/PurchasingServiceProviderForTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/helpers/responses.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingActivityBroadcastReceiverTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingActivityTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingDelegateTest.kt
Labels: refactor

#1099 [PurchaseTester] Add option to purchase an arbitrary product id
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  examples/purchase-tester/src/main/res/values/strings.xml
Labels: enhancement, feat
