Repository RevenueCat/purchases-android, pull requests merged in 2023-05, with the labels that each got.

#959 Add support for product_plan_identifier for offline customer info
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
Labels: fix

#995 Fix `OfflineCustomerInfoCalculatorTest` `Unresolved reference: ProducType`
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
Labels: fix

#980 Fix purchases integration tests
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: test

#988 Add backend integration tests and test product entitlement mapping endpoint
  .circleci/config.yml
  common/build.gradle
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/Constants.kt
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/LoadShedderBackendIntegrationTest.kt
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
  fastlane/Fastfile
  fastlane/README.md
Labels: test

#997 Fix flaky test in OfflineCustomerInfoCalculatorTest
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
Labels: fix

#993 Fix build_magic_weather lane
  examples/MagicWeather/app/build.gradle
  examples/MagicWeather/gradle.properties
  fastlane/Fastfile
Labels: build

#999 Fail offline entitlements computation if product entitlement mapping not available
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor

#998 Fix `PurchasesIntegrationTest` building issue (#996 into main)
  integration-tests/build.gradle
  integration-tests/src/androidTest/java/com/revenuecat/purchases/integrationtests/IntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
Labels: test

#1003 Query only active purchases when generating offline entitlements customer info
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProduct.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: refactor

#1005 CAT-859 Expose whether or not a SubscriptionOption is Prepaid in the SDK
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/SubscriptionOptionTest.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
Labels: feat

#1009 Bump dokka to 1.8.10 to support Gradle 8
  build.gradle
Labels: fix

#1008 Support forcing server errors for tests
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
Labels: test

#942 Workaround bug in android 4 for JSON objects with List<String>
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/MapConverter.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/MapConverterTest.kt
Labels: fix

#1011 Extracts setup and teardown to BasePurchasesTest
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: test

#1014 Disable offline entitlements in observer mode
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
Labels: refactor

#1006 Add offline entitlements integration tests
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsFreshInstallIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: test

#1019 Fix integration tests in CI
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
Labels: test

#1002 Add completion callback to syncPurchases API
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/main/java/com/revenuecat/purchases/interfaces/SyncPurchasesCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
Labels: feat

#985 Support DEFERRED mode
  api-tester/src/main/java/com/revenuecat/apitester/java/GoogleProrationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleProrationModeAPI.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleProrationMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/ProductChangeCallback.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
Labels: feat

#1013 `Offering` metadata
  api-tester/src/main/java/com/revenuecat/apitester/java/OfferingAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingParser.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  public/src/main/java/com/revenuecat/purchases/Offering.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
  utils/build.gradle
  utils/src/main/java/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
  utils/src/main/java/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
  utils/src/test/java/com/revenuecat/purchases/utils/JSONArrayExtensionsTest.kt
  utils/src/test/java/com/revenuecat/purchases/utils/JSONObjectExtensionsTest.kt
Labels: feat

#1023 Disable offline entitlements temporarily
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor

#1027 Refactor offerings code out of Purchases
  common/src/main/java/com/revenuecat/purchases/common/GoogleOfferingParser.kt
  common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsFactory.kt
  common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/OfferingParserFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: refactor

#1017 Perform product entitlement mapping request after more critical requests
  common/src/defaults/kotlin/com/revenuecat/purchases/common/DispatcherConstants.kt
  common/src/integrationTest/kotlin/com/revenuecat/purchases/common/DispatcherConstants.kt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/Dispatcher.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: perf

#1028 Store offerings response in SharedPreferences
  common/src/main/java/com/revenuecat/purchases/common/caching/DateExtensions.kt
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsCache.kt
  common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/caching/DateExtensionsTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
Labels: refactor

#1029 Get offerings response from disk cache if available
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfferingStrings.kt
Labels: feat

#1021 Updated readme to include links to migration guides
  README.md
  migrations/v5-MIGRATION.md
Labels: docs

#1030 Reenable offline entitlements
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
Labels: refactor

#1016 PurchaseTester: Add new UI to configure internal proxy behavior
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LoginFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/proxysettings/ProxyMode.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/proxysettings/ProxySettingsBottomSheetFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/proxysettings/ProxySettingsBottomSheetViewModel.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/proxysettings/ProxySettingsState.kt
  examples/purchase-tester/src/main/res/layout/fragment_configure.xml
  examples/purchase-tester/src/main/res/layout/fragment_login.xml
  examples/purchase-tester/src/main/res/layout/fragment_offering.xml
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  examples/purchase-tester/src/main/res/layout/fragment_proxy_settings_bottom_sheet.xml
  examples/purchase-tester/src/main/res/navigation/nav_graph.xml
  examples/purchase-tester/src/main/res/values/strings.xml
Labels: test

#1032 Fix billing connection error when querying purchases early in the process lifetime
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: fix

#1039 Improve offline entitlements logs to mention limitations of this mode
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor
