Repository RevenueCat/purchases-android, pull requests merged in 2023-07, with the labels that each got.

#1096 Add await offerings
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#1111 Trusted entitlements: Use new signature verification format
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/main/java/com/revenuecat/purchases/strings/NetworkStrings.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
Labels: refactor

#1118 Trusted entitlements: Support API key and url in signature
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/verification/SigningManager.kt
  common/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  common/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
Labels: refactor

#1120 Fix flaky integration tests: Wait for coroutines to finish before continuing
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
Labels: test

#1123 Fix integration tests and change to a different project
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
Labels: test

#1124 Trusted entitlements: Remove decoding of url to verify signatures
  purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SigningManager.kt
  purchases/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
Labels: refactor

#1117 Trusted entitlements: New trusted entitlements signature format
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SignatureVerificationMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SigningManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/NetworkStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/verification/SignatureVerificationModeTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
Labels: refactor

#1105 `Trusted Entitlements`: stable
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfosAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfos.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementVerificationMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/CustomerInfoFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
Labels: feat

#1125 Fix load shedder integration tests
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: test

#1128 Fix issue updating customer info on app open
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: fix

#1129 Fix release path after module refactor
  fastlane/Fastfile
Labels: build

#1126 Update MagicWeather dependencies to latest versions
  examples/MagicWeather/gradle/libs.versions.toml
Labels: build

#1132 Trusted entitlements: Improve signature verification error log
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
Labels: docs

#1133 R8: Do not warn about amazon classes in purchases module
  purchases/consumer-rules.pro
Labels: build

#1134 Trusted entitlements: Add isVerified propety to VerificationResult enum
  api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/VerificationResult.kt
  purchases/src/test/java/com/revenuecat/purchases/VerificationResultTest.kt
Labels: refactor

#1136 Trusted entitlements: Support post params hash header
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBackend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BackendHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/HTTPRequest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/verification/SigningManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/LoadShedderBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientVerificationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/verification/SigningManagerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
Labels: HOLD, refactor

#1137 Diagnostics: Add diagnostics for FEATURE_NOT_SUPPORTED error
  config/detekt/detekt-baseline.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsCounterName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/utils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: feat

#1141 Add internal customEntitlementsComputation mode to app config
  purchases/src/main/kotlin/com/revenuecat/purchases/DangerousSettings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/test/java/com/revenuecat/purchases/DangerousSettingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
Labels: refactor

#1145 Add header to requests when in custom entitlement computation mode
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
Labels: refactor

#1143 Remove integration test flavor
  .circleci/config.yml
  .run/Debug tests.run.xml
  .run/Purchases Integration Tests.run.xml
  .run/Release tests.run.xml
  base-application.gradle
  fastlane/Fastfile
  gradle.properties
  library.gradle
  purchases/build.gradle
  purchases/src/androidTest/AndroidManifest.xml
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/MainActivity.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/factories/StoreProductFactory.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsFreshInstallIntegrationTest.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt
  purchases/src/integrationTest/AndroidManifest.xml
  purchases/src/integrationTest/kotlin/com/revenuecat/purchases/common/DispatcherConstants.kt
  purchases/src/integrationTest/res/mipmap-hdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-hdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-mdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-mdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xxhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xxhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xxxhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xxxhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/values/colors.xml
  purchases/src/integrationTest/res/values/strings.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Dispatcher.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/DispatcherConstants.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/DispatcherTest.kt
Labels: refactor

#1148 Make customEntitlementComputation singular
  purchases/src/main/kotlin/com/revenuecat/purchases/DangerousSettings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  purchases/src/test/java/com/revenuecat/purchases/DangerousSettingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
Labels: refactor

#1144 Creates PurchasesOrchestrator
  config/detekt/detekt-baseline.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#1155 CI: make all Codecov jobs informational
  codecov.yml
Labels: ci

#1151 CustomEntitlementsComputation: Prevent posting subscriber attributes in post receipt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
Labels: feat

#1152 CustomEntitlementsComputation: disable first listener callback when set
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoUpdateHandler.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoUpdateHandlerTest.kt
Labels: feat

#1153 CustomEntitlementComputation: New Purchases class
  api-tester/src/defaults/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  build.gradle
  config/detekt/detekt-baseline.xml
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/purchasesExtensions.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsFreshInstallIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/ListenerConversionsCommon.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesCallbackTypes.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#1154 CustomEntitlementComputation: Create different PurchasesConfiguration that requires an appUserId parameter
  .run/Debug tests (customEntitlementComputation flavor).run.xml
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  build.gradle
  feature/amazon/src/customEntitlementComputationDebug/kotlin/com/revenuecat/purchases/amazon/AmazonConfiguration.kt
  feature/amazon/src/defaults/kotlin/com/revenuecat/purchases/amazon/AmazonConfiguration.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
  purchases/src/testCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/testCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor

#1159 CustomEntitlementComputation: Generate dokka docs only for defaults flavor
  purchases/build.gradle
Labels: docs

#1158 CustomEntitlementComputation: Remove custom entitlement computation flavor for amazon module
  feature/amazon/build.gradle
  feature/amazon/src/customEntitlementComputationDebug/kotlin/com/revenuecat/purchases/amazon/AmazonConfiguration.kt
  feature/amazon/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonConfiguration.kt
  library.gradle
  purchases/build.gradle
Labels: refactor

#1156 Add switchUser
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/IdentityStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  purchases/src/testCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesLoginTests.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#1142 purchase coroutine
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesTransactionExceptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesTransactionExceptionAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseResult.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesException.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesTransactionException.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTransactionExceptionTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#1161 Fix tests in customEntitlementComputation after merges
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: test

#1160 Adds CustomEntitlementComputationSample
  build.gradle
  examples/CustomEntitlementComputationSample/.gitignore
  examples/CustomEntitlementComputationSample/app/.gitignore
  examples/CustomEntitlementComputationSample/app/build.gradle
  examples/CustomEntitlementComputationSample/app/proguard-rules.pro
  examples/CustomEntitlementComputationSample/app/src/main/AndroidManifest.xml
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/CustomEntitlementComputationApp.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/MainActivity.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/data/Constants.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainState.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/ui/theme/Color.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/ui/theme/Theme.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/ui/theme/Type.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/utils/ContextExtensions.kt
  examples/CustomEntitlementComputationSample/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/drawable/ic_launcher_background.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/drawable/ic_user_black_24dp.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/drawable/ic_weather_black_24dp.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  examples/CustomEntitlementComputationSample/app/src/main/res/values/strings.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/values/themes.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/xml/backup_rules.xml
  examples/CustomEntitlementComputationSample/app/src/main/res/xml/data_extraction_rules.xml
  examples/CustomEntitlementComputationSample/build.gradle
  examples/CustomEntitlementComputationSample/gradle.properties
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/CustomEntitlementComputationSample/gradle/wrapper/gradle-wrapper.jar
  examples/CustomEntitlementComputationSample/gradle/wrapper/gradle-wrapper.properties
  examples/CustomEntitlementComputationSample/gradlew
  examples/CustomEntitlementComputationSample/gradlew.bat
  examples/CustomEntitlementComputationSample/settings.gradle
Labels: docs

#1162 Use purchase coroutine in CustomEntitlementComputationSample
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
Labels: refactor

#1149 Add publish system for customEntitlementComputation package
  fastlane/Fastfile
Labels: ci

#1166 Update Custom Entitlements Sample app
  examples/CustomEntitlementComputationSample/app/src/main/AndroidManifest.xml
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/CustomEntitlementComputationApp.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoDetailScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoEventList.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/ExplanationScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainState.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
Labels: feat

#1168 CustomEntitlementComputation: Configure method for customEntitlementComputation mode
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/testCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/testCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
Labels: refactor

#1167 Custom entitlements: add README and other improvements
  examples/CustomEntitlementComputationSample/README.md
  examples/CustomEntitlementComputationSample/Sample screenshot.png
  examples/CustomEntitlementComputationSample/app/build.gradle
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoEventList.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/CustomEntitlementComputationSample/sample_screenshot.png
  examples/CustomEntitlementComputationSample/settings.gradle
Labels: feat

#1172 Revert "[AUTOMATIC] Release/6.8.0"
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  docs/index.html
  gradle.properties
  library.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Config.kt
Labels: ci

#1164 CustomEntitlementComputation: Integration tests
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesTestConfigurationExtensions.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesTestConfigurationExtensions.kt
Labels: refactor

#1175 Run linter in CustomEntitlementComputation sample app
  build.gradle
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/data/CustomerInfoEvent.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoDetailScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/CustomerInfoEventList.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/ExplanationScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainState.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
Labels: refactor

#1176 Auto-update sample apps SDK versions
  .circleci/config.yml
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  fastlane/Fastfile
  fastlane/README.md
Labels: build

#1179 Update Kotlin from 1.6.21 to 1.7.21
  gradle/libs.versions.toml
  purchases/src/main/kotlin/com/revenuecat/purchases/common/logUtils.kt
Labels: build

#1181 Update AGP to 8.1.0
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  gradle/libs.versions.toml
Labels: build

#1183 Support receiving productId with basePlanId in upgrades/downgrades
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Constants.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#1184 Make coroutines APIs stable
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/trustedentitlements/TrustedEntitlementsInformationalModeIntegrationTest.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
Labels: feat

#1182 Remove unnecessary buildToolsVersion config
  base-application.gradle
  examples/MagicWeather/app/build.gradle
  library.gradle
Labels: build

#1185 Add setup_dev
  CONTRIBUTING.md
  fastlane/Fastfile
  fastlane/README.md
  scripts/pre-commit.sh
Labels: docs
