Repository RevenueCat/purchases-android, pull requests merged in 2023-11, with the labels that each got.

#1420 Improvements on BillingWrapper retrying mechanism
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: fix

#1426 `StoreProduct`: new `pricePerWeek` and `pricePerYear`
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  gradle/libs.versions.toml
  purchases/build.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/models/Period.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/StoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerMonthTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerPeriodTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerWeekTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/PriceExtensionsPricePerYearTest.kt
Labels: feat

#1425 `Paywalls`: new `{{ sub_relative_discount }}` variable
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ProcessedLocalizedConfiguration.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Labels: RevenueCatUI

#1427 `Paywalls`: new `{{ sub_price_per_week }}` variable
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Labels: RevenueCatUI

#1432 Paywalls: Add initial snapshot testings for RevenueCatUI library
  .circleci/config.yml
  .gitignore
  fastlane/.purchases-android-snapshots-commit
  fastlane/Fastfile
  fastlane/README.md
  ui/revenuecatui/.gitignore
  ui/revenuecatui/build.gradle
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/BasePaparazziTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/TemplateSnapshotTest.kt
  ui/revenuecatui/src/test/snapshots/images/.gitkeep
Labels: test, RevenueCatUI

#1433 Fix RevenueCatUI API issues and add API tests
  api-tester/build.gradle
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/FontProviderAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallActivityLauncherAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallResultAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/FontProviderAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallActivityLauncherAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallDialogOptionsAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallListenerAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallOptionsAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallResultAPI.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontStyleParceler.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFont.kt
Labels: test, RevenueCatUI

#1437 `Offering`: restore constructor with no `PaywallData`
  api-tester/src/main/java/com/revenuecat/apitester/java/OfferingAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
Labels: refactor

#1436 Paywalls: Store paywall events on disk and API (1)
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallTrackingAPI.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsFileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallStoredEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/DateSerializer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/URLSerializer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/UUIDSerializer.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventSerializationTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor, RevenueCatUI

#1439 `Paywalls`: improve Japanese localization
  ui/revenuecatui/src/main/res/values-ja/strings.xml
Labels: RevenueCatUI

#1435 Improve fullscreen templates in landscape orientation
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/IntSizeExtensions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
Labels: refactor, RevenueCatUI

#1443 Remove side effect from setting purchasesUpdatedListener
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: refactor

#1441 `PaywallActivityLauncher`: new constructor for a generic `ActivityResultCaller`
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallActivityLauncherAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallActivityLauncherAPI.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
Labels: RevenueCatUI

#1453 Lower request jitter log level from warning to debug
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
Labels: refactor

#1454 `Paywalls`: improve error log when images fail to load
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
Labels: RevenueCatUI

#1455 `CircleCI`: fix `record-revenuecatui-snapshots`
  .circleci/config.yml
Labels: ci

#1442 Paywalls: Support sending paywall events to servers (2)
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallBackendEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventRequest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallStoredEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/JsonElementExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendPaywallEventTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventRequestSerializationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/JsonElementExtensionsTest.kt
Labels: refactor, RevenueCatUI

#1445 Paywalls: Add paywall events flush logic and tests (3)
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
Labels: refactor

#1446 Paywalls: Move logic for events file helper to common generic class (4)
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventRequest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsFileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallStoredEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/Event.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/EventsFileHelper.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendPaywallEventTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventRequestSerializationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventSerializationTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
Labels: refactor

#1451 Paywall events: Handle errors parsing specific paywall event lines
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/EventsFileHelper.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsManagerTest.kt
Labels: refactor

#1447 Paywalls: Track paywall events
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Labels: refactor

#1452 Paywall events: Send paywall data with post receipt requests
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallPresentedCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallPostReceiptData.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#1458 Update gradle plugin to version 8.1.1
  gradle/libs.versions.toml
Labels: build

#1461 `Snapshots`: fix Fastlane job
  fastlane/Fastfile
Labels: ci

#1456 Update circleci orb to latest version
  .circleci/config.yml
Labels: ci

#1462 Bump compile/target version to 34
  build.gradle
  examples/CustomEntitlementComputationSample/app/build.gradle
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeather/build.gradle
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeatherCompose/app/build.gradle
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  gradle/libs.versions.toml
Labels: build

#1464 `Paywalls`: improve image loading
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
Labels: perf, RevenueCatUI

#1469 Paywalls: Support condensed footer in template 4
  fastlane/.purchases-android-snapshots-commit
  fastlane/Fastfile
  fastlane/README.md
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt
Labels: RevenueCatUI

#1467 Paywalls: Fix purchasing regression by providing real activity
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/ContextExtensions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/WindowHelper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Labels: refactor

#1468 Prevents queryPurchases from being called twice
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: fix

#1476 Update AGP to 8.1.3
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  gradle/libs.versions.toml
Labels: build

#1477 Fix flaky test in BillingWrapperTest
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: test

#1481 Update Billing client to 6.1.0
  gradle/libs.versions.toml
  purchases/src/test/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcherTests.kt
Labels: dependencies

#1444 Add retries to queryProductDetailsAsync
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingResponse.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/BillingClientUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingResponseCodeTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
Labels: refactor

#1482 Add method to get storefront for Google and Amazon stores
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/MockHandlerFactory.kt
Labels: refactor

#1483 Use state listener in Amazon store
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
Labels: refactor

#1470 Paywalls: Add paywalls UI tests
  .circleci/config.yml
  ui/revenuecatui/build.gradle
  ui/revenuecatui/src/androidTest/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallUITest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/TestTag.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
Labels: test

#1484 Add `X-Storefront` header to requests
  config/detekt/detekt-baseline.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/StorefrontProvider.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt
Labels: refactor

#1478 `Paywalls`: Fix Turkish translation
  ui/revenuecatui/src/main/res/values-tr/strings.xml
Labels: RevenueCatUI

#1486 Create a BaseBillingUseCaseTest
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
Labels: test

#1488 Check diagnostics file size in background thread
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
Labels: fix

#1489 Initialize shared preferences lazily
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
Labels: refactor

#1460 Add retries to queryPurchases
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/BillingClientUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCase.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCaseTest.kt
Labels: refactor

#1490 Add retries with backoff and different treatment to SERVICE_UNAVAILABLE
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/BillingClientUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostTransactionWithProductDetailsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/GetBillingConfigUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCaseTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor

#1487 ConsumePurchaseUseCase
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCase.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
Labels: refactor

#1493 Refactor findPurchaseInPurchaseHistory
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
Labels: refactor

#1492 Add AcknowledgePurchaseUseCase
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCase.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
Labels: refactor

#1496 Avoid creating threads when dispatching tasks
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Dispatcher.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/SyncDispatcher.kt
Labels: perf

#1497 Cleanup warnings in AcknowledgePurchaseUseCaseTest
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
Labels: test

#1500 Fixes on generate_snapshots_RCUI lane
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#1499 Fix white line around buttons in Template 4
  fastlane/.purchases-android-snapshots-commit
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt
Labels: fix

#1507 Paywalls: Auto-close paywall activity if restore grants required entitlement identifier
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallResultAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallResultAPI.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallResult.kt
Labels: RevenueCatUI
