Repository RevenueCat/purchases-android, pull requests merged in 2023-01, with the labels that each got.

#725 remove stalebot in favor of SLAs in Zendesk
  .github/stale.yml
Labels: ci

#722 Add clarifying comment for multiline
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
Labels: docs

#729 Deprecate CustomerInfo sku references, update to product Id
  api-tester/src/main/java/com/revenuecat/apitester/java/CustomerInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/CustomerInfoAPI.kt
  common/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
Labels: refactor

#726 [CF-1069] [CSDK-484] Replace getSubscriptionSkus and getNonSubscriptionSkus with getProducts
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#728 [CF-997] Support upgrade/downgrade
  api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
  common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
Labels: refactor

#731 Use toString in errorLog so that underlying message gets logged too
  common/src/main/java/com/revenuecat/purchases/common/logUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: enhancement, refactor

#733 [CF-1145] Upgrade/downgrade support in purchase tester
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainApplication.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
Labels: feat

#734 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#742 Fix crash when cleaning old attribution data if SharedPreferences has a null key
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
Labels: fix

#740 Default ProrationMode to IMMEDIATE_WITHOUT_PRORATION
  api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#743 Release 6.0.0 alpha.1
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: breaking

#744 Revert "PurchaseOption -> SubscriptionOption rename"
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchaseOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchaseOptionApi.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PurchaseOptionExtensions.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  examples/purchase-tester/src/main/res/values/strings.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/GooglePurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: refactor

#739 [CF-1135] Remove requirement for `StoreProduct` when purchasing a `PurchaseOption`
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchaseOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchaseOptionApi.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/BillingAbstract.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonBilling.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/purchaseOptionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GooglePurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/GooglePurchasingData.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchaseOption.kt
  public/src/main/java/com/revenuecat/purchases/models/PurchasingData.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/PurchaseStrings.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: refactor

#750 Add codecov
  .circleci/config.yml
Labels: ci

#727 Fixed Readme.MD
  examples/MagicWeather/README.md
Labels: docs

#749 Redo rename PurchaseOption -> SubscriptionOption
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchaseOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchaseOptionApi.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  examples/purchase-tester/src/main/res/values/strings.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: breaking, docs

#751 [CF-1148] Add proration mode
  api-tester/src/main/java/com/revenuecat/apitester/java/GoogleProrationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleProrationModeAPI.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/GoogleProrationMode.kt
Labels: feat

#752 [CF-1147] Use GoogleProrationMode in purchases
  api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
Labels: feat

#755 Avoid syncing attributes for users with blank user ids
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManager.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
Labels: fix

#753 Add `Purchases.logLevel` and deprecate `Purchases.debugLogsEnabled`
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  common/src/main/java/com/revenuecat/purchases/common/logUtils.kt
  common/src/main/java/com/revenuecat/purchases/common/logWrapper.kt
  common/src/test/java/com/revenuecat/purchases/common/LogHandlerTest.kt
  common/src/test/java/com/revenuecat/purchases/common/LogUtilsTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LogLevel.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/LogMessage.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/TesterLogHandler.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/ProductDataHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseUpdatesHandlerTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/handler/UserDataHandlerTest.kt
  public/src/main/java/com/revenuecat/purchases/LogHandler.kt
  public/src/main/java/com/revenuecat/purchases/LogLevel.kt
  public/src/test/java/com/revenuecat/purchases/LogLevelTest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesLoggerTest.kt
Labels: feat

#754 [CF-1119] - Default offer now uses best offer logic (longest free, best savings, base plan)
  feature/google/src/main/java/com/revenuecat/purchases/google/findBestOffer.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/FindBestOfferTest.kt
  public/src/main/java/com/revenuecat/purchases/models/GooglePurchasingData.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#736 Clean up Google-related TODOs
  api-tester/src/main/java/com/revenuecat/apitester/java/PackageAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PackageAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  common/src/test/java/com/revenuecat/purchases/common/OfferingsTest.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/PackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
  examples/purchase-tester/src/main/res/layout/package_card.xml
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/billingClientParamBuilders.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  public/src/main/java/com/revenuecat/purchases/CustomerInfo.kt
  public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt
  public/src/main/java/com/revenuecat/purchases/Package.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  public/src/main/java/com/revenuecat/purchases/models/RecurrenceMode.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/listenerConversions.kt
  utils/src/main/java/com/revenuecat/purchases/utils/JSONObjectParceler.kt
Labels: refactor

#762 [CF1120] - Update SDK docs for default offer logic
  migrations/v6-MIGRATION.md
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: docs

#764 Release/6.0.0-alpha.2
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  Gemfile.lock
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  fastlane/Pluginfile
  gradle.properties
  library.gradle
Labels: next_release
