Repository RevenueCat/purchases-android, pull requests merged in 2023-08, with the labels that each got.

#1180 Remove customEntitlementComputation flavor for non-purchases modules
  feature/amazon/build.gradle
  library.gradle
  purchases/build.gradle
Labels: build

#1075 Debug view: Initial UI + Usage in MagicWeatherCompose
  api-tester/build.gradle
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesDebugViewAPI.kt
  config/detekt/detekt.yml
  debugview/.gitignore
  debugview/build.gradle
  debugview/consumer-rules.pro
  debugview/proguard-rules.pro
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatViewModel.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/InternalDebugRevenueCatScreenViewModel.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingGroupState.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingScreenState.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingState.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingGroup.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingText.kt
  debugview/src/main/AndroidManifest.xml
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatBottomSheet.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatScreen.kt
  debugview/src/main/res/values/strings.xml
  debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
  debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
  examples/MagicWeatherCompose/app/build.gradle
  examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  examples/MagicWeatherCompose/settings.gradle
  gradle/libs.versions.toml
  settings.gradle
Labels: test

#1186 Debug view: Add offerings section and purchasing capabilities
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesDebugViewAPI.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/ContextExtensions.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatViewModel.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/InternalDebugRevenueCatScreenViewModel.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/InternalDebugRevenueCatScreenViewModelFactory.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingScreenState.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/models/SettingState.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingGroup.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingOffering.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingText.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatBottomSheet.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatScreen.kt
  debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
  debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
  examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/main/MainScreen.kt
Labels: test

#1190 Fix NoSuchElementException by using poll when accessing serviceRequests
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
Labels: fix

#1187 Debugview: Add snapshot tests for debug view using Paparazzi
  .circleci/config.yml
  debugview/build.gradle
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatBottomSheet.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingGroup.kt
  debugview/src/debug/kotlin/com/revenuecat/purchases/debugview/settings/SettingOffering.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/DebugRevenueCatViewModel.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/models/SettingGroupState.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/models/SettingScreenState.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/models/SettingState.kt
  debugview/src/main/kotlin/com/revenuecat/purchases/debugview/models/TestModels.kt
  debugview/src/release/kotlin/com/revenuecat/purchases/debugview/InternalDebugRevenueCatScreen.kt
  debugview/src/test/java/com/revenuecat/purchases/debugview/DebugViewSnapshotTest.kt
  debugview/src/test/snapshots/images/com.revenuecat.purchases.debugview_DebugViewSnapshotTest_configuredStateDisplaysCorrectly.png
  debugview/src/test/snapshots/images/com.revenuecat.purchases.debugview_DebugViewSnapshotTest_notConfiguredStateDisplaysCorrectly.png
  fastlane/Fastfile
  fastlane/README.md
  gradle.properties
  gradle/libs.versions.toml
Labels: test

#1192 Debug view: Support deploying both noop and debug version of `debugview` package
  examples/MagicWeatherCompose/settings.gradle
  fastlane/Fastfile
  ui/debugview/build.gradle
  ui/debugview/gradle.properties
Labels: build

#1199 DENG-494: Fix offering metadata not fulling expanding
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/JSONArrayExtensionsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/JSONObjectExtensionsTest.kt
Labels: fix

#1200 Fix deploying extra packages
  fastlane/Fastfile
Labels: build

#1193 Relax consumer rules to allow for better minifying and obfuscation
  examples/MagicWeather/app/proguard-rules.pro
  examples/purchase-tester/proguard-rules.pro
  feature/amazon/consumer-rules.pro
  integration-tests/proguard-rules.pro
  purchases/consumer-rules.pro
Labels: build

#1194 Optimize diagnostics file management
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/FileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/AndroidVersionUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/FileExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: perf, refactor

#1204 Optimize SDK initialization when requests executed before any activity starts
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBackend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BackendHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/NetworkStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
Labels: perf

#1203 Use real debug view dependencies in magic weather compose
  examples/MagicWeatherCompose/app/build.gradle
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  examples/MagicWeatherCompose/settings.gradle
Labels: refactor

#1206 Unify caching offerings and updating update timestamp
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
Labels: refactor

#1211 CustomEntitlementComputation: Add `restorePurchases`
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/ListenerConversionsCommon.kt
Labels: refactor

#1212 Send `initiation_source` in post receipt requests
  purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptInitiationSource.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptInitiationSourceTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostTransactionWithProductDetailsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor

#1214 Rename `queue` initiation source to `unsynced_active_purchases`
  purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptInitiationSource.kt
  purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptInitiationSourceTest.kt
Labels: refactor
