Repository RevenueCat/purchases-android, pull requests merged in 2023-04, with the labels that each got.

#933 Add load shedder integration tests to V4 version
  build.gradle
  examples/purchase-tester-java/build.gradle
  examples/purchase-tester/build.gradle
  integration-tests/build.gradle
  library.gradle
  purchases/build.gradle
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/ProductDetailsFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/factories/PurchaseDetailsFactory.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/helpers/BillingAbstractMockHelper.kt
  purchases/src/integrationTest/AndroidManifest.xml
  purchases/src/integrationTest/kotlin/com/revenuecat/purchases/MainActivity.kt
  purchases/src/integrationTest/res/mipmap-hdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-hdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-mdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-mdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xxhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xxhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/mipmap-xxxhdpi/ic_launcher.png
  purchases/src/integrationTest/res/mipmap-xxxhdpi/ic_launcher_round.png
  purchases/src/integrationTest/res/values/colors.xml
  purchases/src/integrationTest/res/values/strings.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: test

#935 Increase heap size
  gradle.properties
Labels: build

#937 Add store getter to purchases instance
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#929 add note about observer mode to v6-migration
  migrations/v6-MIGRATION.md
Labels: docs

#885 Compute CustomerInfo from a list of purchases
  common/src/main/java/com/revenuecat/purchases/common/errors.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProduct.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/CustomerInfoStrings.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: feat

#944 `toPurchasesError` back to internal
  common/src/main/java/com/revenuecat/purchases/common/errors.kt
Labels: fix

#940 Report load shedder integration tests results in slack for V5
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
Labels: test

#946 Add verification for entitlement granting to integration tests
  fastlane/Fastfile
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: test

#930 [CF-1325] Add missing presentedOfferingId to `StoreProduct` and `SubscriptionOption`
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/OfferingParser.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/AmazonStoreProduct.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeProductConversions.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/AmazonOfferingsTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/StoreProductTest.kt
  feature/amazon/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeProductConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/StoreProductTest.kt
  migrations/v6-MIGRATION.md
  public/src/main/java/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt
  public/src/main/java/com/revenuecat/purchases/models/SubscriptionOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchaseParamsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: fix

#945 Extract all customer info json strings
  common/src/main/java/com/revenuecat/purchases/common/Constants.kt
  common/src/main/java/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  common/src/main/java/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  common/src/main/java/com/revenuecat/purchases/common/responses/CustomerInfoResponseJsonKeys.kt
Labels: refactor

#943 Add `PaymentMode` on to `PricingPhase` to describe behavior for offers
  api-tester/src/main/java/com/revenuecat/apitester/java/OfferPaymentModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PricingPhaseAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferPaymentModeAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PricingPhaseAPI.kt
  public/src/main/java/com/revenuecat/purchases/models/OfferPaymentMode.kt
  public/src/main/java/com/revenuecat/purchases/models/PricingPhase.kt
  public/src/test/java/com/revenuecat/purchases/common/models/PricingPhaseTest.kt
Labels: feat

#947 Release/6.1.0
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  common/src/main/java/com/revenuecat/purchases/common/Config.kt
  docs/index.html
  gradle.properties
  library.gradle
Labels: next_release

#876 Add diagnostics tracking for BC5 google methods
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventName.kt
  common/src/main/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  common/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: refactor

#953 Remove flavors temporarily to fix deployment
  base-application.gradle
  feature/amazon/build.gradle
  gradle.properties
  library.gradle
  purchases/build.gradle
Labels: build, fix

#952 [CF-1324] Fix personalizedPrice defaulting to false
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#939 Added ENTITLEMENTS_COMPUTED_ON_DEVICE
  api-tester/src/main/java/com/revenuecat/apitester/java/VerificationResultAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VerificationResultAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfoTest.kt
  common/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  utils/src/main/java/com/revenuecat/purchases/VerificationResult.kt
Labels: feat

#934 Automate load shedder integration tests for V4
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
  purchases/.gitignore
  purchases/build.gradle
Labels: test

#941 Report load shedder integration tests results in slack for V4
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
Labels: test

#965 Extract detekt job from test job
  .circleci/config.yml
Labels: ci

#966 Fix storing test results
  .circleci/config.yml
Labels: ci

#958 Add non-subscriptions support to offline customer info
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/billingClientStubs.kt
Labels: fix

#962 Add back integration test flavors
  base-application.gradle
  feature/amazon/build.gradle
  gradle.properties
  library.gradle
  purchases/build.gradle
Labels: test

#963 Add isServerDown to error callback for postReceipt and getCustomerInfo requests
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  feature/subscriber-attributes/src/main/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesPoster.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostingTransactionsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: refactor

#975 Upgrade to AGP 8.0
  .sdkmanrc
  base-application.gradle
  build.gradle
  common/build.gradle
  common/consumer-rules.pro
  examples/MagicWeather/app/build.gradle
  examples/MagicWeather/app/src/main/AndroidManifest.xml
  examples/MagicWeather/app/src/main/java/com/revenuecat/sample/ui/paywall/PaywallFragment.kt
  examples/MagicWeather/build.gradle
  examples/MagicWeather/gradle.properties
  examples/MagicWeather/gradle/wrapper/gradle-wrapper.properties
  examples/purchase-tester/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#949 Add entitlement verification checks to load shedder integration tests v4
  fastlane/Fastfile
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestIntegrationTest/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: test

#972 Add back integration tests automation
  .circleci/config.yml
Labels: test

#978 Store and return ETag last refresh time header
  common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/ETagManager.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/HTTPRequest.kt
  common/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/ETagManagerTest.kt
Labels: perf

#977 Add proration modes to post to backend
  .idea/codeStyles/Project.xml
  api-tester/src/main/java/com/revenuecat/apitester/java/GoogleProrationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleProrationModeAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/ReceiptInfo.kt
  common/src/main/java/com/revenuecat/purchases/common/ReplaceProductInfo.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  feature/amazon/src/main/java/com/revenuecat/purchases/amazon/storeTransactionConversions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingFlowParamsExtensions.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/PurchaseContext.kt
  feature/google/src/main/java/com/revenuecat/purchases/google/storeTransactionConversions.kt
  feature/google/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  public/src/main/java/com/revenuecat/purchases/ProrationMode.kt
  public/src/main/java/com/revenuecat/purchases/models/GoogleProrationMode.kt
  public/src/main/java/com/revenuecat/purchases/models/StoreTransaction.kt
  public/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  test-utils/src/main/java/com/revenuecat/purchases/utils/ParcelizationTestHelper.kt
Labels: feat

#964 Support enabling/disabling offline entitlements
  common/src/main/java/com/revenuecat/purchases/common/AppConfig.kt
  common/src/main/java/com/revenuecat/purchases/common/Backend.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
  feature/identity/src/main/java/com/revenuecat/purchases/identity/IdentityManager.kt
  feature/identity/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  feature/subscriber-attributes/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/CustomerInfoHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesTest.kt
  strings/src/main/java/com/revenuecat/purchases/strings/CustomerInfoStrings.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor

#976 Update product entitlement mapping request to new format
  common/src/main/java/com/revenuecat/purchases/common/caching/DeviceCache.kt
  common/src/main/java/com/revenuecat/purchases/common/networking/Endpoint.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMapping.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProduct.kt
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcher.kt
  common/src/test/java/com/revenuecat/purchases/common/BackendTest.kt
  common/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  common/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/ProductEntitlementMappingTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/PurchasedProductsFetcherTest.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/productEntitlementMappingFactory.kt
  strings/src/main/java/com/revenuecat/purchases/strings/OfflineEntitlementsStrings.kt
Labels: refactor

#989 Clear cached customer info upon entering offline entitlements mode
  common/src/main/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManager.kt
  common/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineEntitlementsManagerTest.kt
Labels: refactor
