Repository RevenueCat/purchases-android, pull requests merged in 2024-11, with the labels that each got.

#1894 Dispatcher catches and rethrows Throwable instead of Exception to avoid swallowing errors
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Dispatcher.kt
Labels: pr:other

#1897 Add `tenjinAnalyticsInstallationId` setter property
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: pr:feat

#1903 Use new web redemption endpoint
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
Labels: pr:other

#1904 Handle `IllegalArgumentException` when opening a Uri in the paywalls
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/UriHandlerExtensions.kt
  ui/revenuecatui/src/main/res/values-ar/strings.xml
  ui/revenuecatui/src/main/res/values-bg/strings.xml
  ui/revenuecatui/src/main/res/values-ca/strings.xml
  ui/revenuecatui/src/main/res/values-cs/strings.xml
  ui/revenuecatui/src/main/res/values-da/strings.xml
  ui/revenuecatui/src/main/res/values-de/strings.xml
  ui/revenuecatui/src/main/res/values-el/strings.xml
  ui/revenuecatui/src/main/res/values-es/strings.xml
  ui/revenuecatui/src/main/res/values-fi/strings.xml
  ui/revenuecatui/src/main/res/values-fr/strings.xml
  ui/revenuecatui/src/main/res/values-he/strings.xml
  ui/revenuecatui/src/main/res/values-hi/strings.xml
  ui/revenuecatui/src/main/res/values-hr/strings.xml
  ui/revenuecatui/src/main/res/values-hu/strings.xml
  ui/revenuecatui/src/main/res/values-id/strings.xml
  ui/revenuecatui/src/main/res/values-it/strings.xml
  ui/revenuecatui/src/main/res/values-ja/strings.xml
  ui/revenuecatui/src/main/res/values-kk/strings.xml
  ui/revenuecatui/src/main/res/values-ko/strings.xml
  ui/revenuecatui/src/main/res/values-ms/strings.xml
  ui/revenuecatui/src/main/res/values-nl/strings.xml
  ui/revenuecatui/src/main/res/values-no/strings.xml
  ui/revenuecatui/src/main/res/values-pl/strings.xml
  ui/revenuecatui/src/main/res/values-pt/strings.xml
  ui/revenuecatui/src/main/res/values-ro/strings.xml
  ui/revenuecatui/src/main/res/values-ru/strings.xml
  ui/revenuecatui/src/main/res/values-sk/strings.xml
  ui/revenuecatui/src/main/res/values-sv/strings.xml
  ui/revenuecatui/src/main/res/values-th/strings.xml
  ui/revenuecatui/src/main/res/values-tr/strings.xml
  ui/revenuecatui/src/main/res/values-uk/strings.xml
  ui/revenuecatui/src/main/res/values-vi/strings.xml
  ui/revenuecatui/src/main/res/values-zh-rHK/strings.xml
  ui/revenuecatui/src/main/res/values-zh-rTW/strings.xml
  ui/revenuecatui/src/main/res/values-zh/strings.xml
  ui/revenuecatui/src/main/res/values/strings.xml
Labels: pr:fix, pr:RevenueCatUI

#1899 Add extra error cases for web purchases redemptions
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/RedeemWebPurchaseListenerAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/IntentExtensionsAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/RedeemWebPurchaseListenerAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/MainActivity.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/IntentExtensions.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/WebPurchaseRedemption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/RCHTTPStatusCodes.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/deeplinks/DeepLinkParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/deeplinks/WebPurchaseRedemptionHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/RedeemWebPurchaseListener.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/deeplinks/WebPurchaseRedemptionHelperTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: pr:other

#1908 Create sample web purchase redemption app
  examples/web-purchase-redemption-sample/.gitignore
  examples/web-purchase-redemption-sample/build.gradle.kts
  examples/web-purchase-redemption-sample/proguard-rules.pro
  examples/web-purchase-redemption-sample/src/main/AndroidManifest.xml
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/Constants.kt
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/Content.kt
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/MainActivity.kt
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/MainApplication.kt
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/ui/theme/Color.kt
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/ui/theme/Theme.kt
  examples/web-purchase-redemption-sample/src/main/java/com/revenuecat/webpurchaseredemptionsample/ui/theme/Type.kt
  examples/web-purchase-redemption-sample/src/main/res/drawable-v24/ic_launcher_foreground.xml
  examples/web-purchase-redemption-sample/src/main/res/drawable/ic_launcher_background.xml
  examples/web-purchase-redemption-sample/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  examples/web-purchase-redemption-sample/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  examples/web-purchase-redemption-sample/src/main/res/mipmap-hdpi/ic_launcher.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-mdpi/ic_launcher.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-xhdpi/ic_launcher.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  examples/web-purchase-redemption-sample/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  examples/web-purchase-redemption-sample/src/main/res/values/colors.xml
  examples/web-purchase-redemption-sample/src/main/res/values/strings.xml
  examples/web-purchase-redemption-sample/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  settings.gradle
Labels: pr:other

#1914 Catch `NoSuchMethodError` on Ads library
  purchases/src/main/kotlin/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcher.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/AttributionStrings.kt
Labels: pr:fix

#1923 [Paywalls V2] Adds `ImageUrls` and `ColorInfo` properties
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/ColorUtils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ImageUrls.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ColorInfoTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ImageUrlsTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1924 [Paywalls V2] Adds `CornerRadiuses`, `Shape` and `MaskShape` properties
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/CornerRadiusesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/MaskShapeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ShapeTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1925 [Paywalls V2] Adds `SizeConstraints`, `Size`, `Padding` and `Shadow` properties
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Padding.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shadow.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/PaddingTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ShadowTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/SizeTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1926 [Paywalls V2] Adds all enum properties
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Alignment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/FitMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/FlexDistribution.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Font.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/AlignmentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FitModeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FlexDistributionTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FontTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1927 [Paywalls V2] Adds `TextComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/LocalizationKey.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TextComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1928 [Paywalls V2] Adds `ImageComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ImageComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1929 [Paywalls V2] Adds `ComponentOverrides`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ComponentOverrides.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ComponentOverridesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ImageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TextComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1930 [Paywalls V2] Adds `StackComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Border.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Dimension.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StackComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/BorderTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/DimensionTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1931 [Paywalls V2] Adds `ButtonComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ButtonComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1932 [Paywalls V2] Adds `PackageComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PackageComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PackageComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1933 [Paywalls V2] Adds `PurchaseButtonComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1935 [Paywalls V2] Adds `PaywallComponentsData`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/Background.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ComponentsConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/Localization.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/LocalizationKey.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponentsData.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/BackgroundTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ComponentsConfigTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/LocalizationDataTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PaywallComponentsDataTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1936 [Paywalls V2] `LocalizationKey` is an inline value class now.
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/Localization.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ComponentOverridesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ComponentsConfigTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ImageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PackageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PaywallComponentsDataTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StackComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StickyFooterComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TextComponentTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1937 [Paywalls V2] Moves any non-component file to a new `common` package.
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PartialComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Background.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverrides.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentsConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/PaywallComponentsData.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ImageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PackageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StackComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StickyFooterComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TextComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/BackgroundTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentOverridesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentsConfigTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/LocalizationDataTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/PaywallComponentsDataTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1938 Introduces an `@InternalRevenueCatAPI` annotation
  purchases/build.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/InternalRevenueCatAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PackageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PartialComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StickyFooterComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Background.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverrides.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentsConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/PaywallComponentsData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Alignment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Border.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Dimension.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/FitMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/FlexDistribution.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Font.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ImageUrls.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Padding.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shadow.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
  ui/revenuecatui/build.gradle
Labels: pr:other

#1939 [Paywalls V2] Makes `TextComponent` public
  build.gradle
  gradle/libs.versions.toml
  purchases/build.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PartialComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverrides.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Alignment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Font.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Padding.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1942 [Paywalls V2] Minimizes Java API
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PackageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StickyFooterComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Background.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverrides.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentsConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/PaywallComponentsData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Border.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Dimension.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ImageUrls.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Padding.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shadow.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#1943 Uses `Sequence` instead of `Stream` to avoid errors due to unavailable Java 8 APIs
  purchases/src/main/kotlin/com/revenuecat/purchases/common/FileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEventsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/EventsFileHelper.kt
  purchases/src/test/java/com/revenuecat/purchases/common/FileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
Labels: pr:fix

#1946 Increase integration test timeout
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
Labels: pr:other
