Repository RevenueCat/purchases-android, pull requests merged in 2024-08, with the labels that each got.

#1803 Publish paywall tester on each release
  .circleci/config.yml
Labels: ci

#1806 Support to round+truncate prices displayed on paywalls for backend-specified countries
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/GoogleListSerializer.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/OfferingImagePreDownloaderTest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template1TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template2TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template3TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template4TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template5TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template7CustomPackagesTestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/templates/Template7TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/MultiTierTemplateConfigurationFactoryTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfigurationFactoryTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Labels: feat

#1809 [Paywalls] Add default locale
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
  purchases/src/test/resources/paywalldata-default-locale-with-missing_current_locale.json
Labels: feat

#1810 [V5] Change device running nightly integration tests
  fastlane/Fastfile
Labels: test

#1811 [V4] Change device running nightly integration tests
  fastlane/Fastfile
Labels: test

#1817 Update `compose-bom` to latest version
  fastlane/.purchases-android-snapshots-commit
  gradle/libs.versions.toml
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template7.kt
Labels: dependencies

#1819 Update debug view snapshot tests
  ui/debugview/src/test/snapshots/images/com.revenuecat.purchases.ui.debugview_DebugViewSnapshotTest_configuredStateDisplaysCorrectly.png
  ui/debugview/src/test/snapshots/images/com.revenuecat.purchases.ui.debugview_DebugViewSnapshotTest_notConfiguredStateDisplaysCorrectly.png
Labels: test

#1814 Rename and result type consolidation
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/MyAppPurchaseLogicAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallOptionsAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PurchaseLogicAPI.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PurchaseLogic.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Labels: refactor

#1821 Converts MagicWeather's Gradle files to Kotlin
  examples/MagicWeather/app/build.gradle
  examples/MagicWeather/app/build.gradle.kts
  examples/MagicWeather/app/proguard-rules.pro
  examples/MagicWeather/build.gradle
  examples/MagicWeather/build.gradle.kts
  examples/MagicWeather/settings.gradle
  examples/MagicWeather/settings.gradle.kts
  fastlane/Fastfile
Labels: build, refactor

#1822 Adds Detekt rules for Compose. Updates detekt to 1.23.6.
  build.gradle
  config/detekt/detekt-baseline.xml
  gradle/libs.versions.toml
Labels: build, ci, dependencies

#1824 [Paywalls] Add spacing between paragraphs and make text go full width so text align applies
  fastlane/.purchases-android-snapshots-commit
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
Labels: fix
