Repository RevenueCat/purchases-android, pull requests merged in 2024-05, with the labels that each got.

#1702 Fix bad copy in log message
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/ConfigureStrings.kt
Labels: fix

#1697 Support non consumable products
  purchases/src/main/kotlin/com/revenuecat/purchases/PostReceiptHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/PostReceiptResponse.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/PurchaseStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostReceiptHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt
Labels: feat

#1704 Fix offline integration tests
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/BaseOfflineEntitlementsIntegrationTest.kt
Labels: test

#1709 Fix non-consumables not getting acknowledged
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
Labels: fix

#1713 Bump amazon SDK version to 3.0.5
  gradle/libs.versions.toml
Labels: dependencies

#1715 Fix purchase tester offerings not reloading
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
Labels: test

#1719 Remove `force-release-without-waiting-for-tests` job
  .circleci/config.yml
Labels: ci
