Repository RevenueCat/purchases-android, pull requests merged in 2024-07, with the labels that each got.

#1769 Add 7.12.0 to CHANGELOG
  CHANGELOG.md
Labels: docs

#1768 Use trimmed API key
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
Labels: fix

#1774 Update migration docs adding back support for `DEFERRED` upgrades
  migrations/v7-MIGRATION.md
Labels: docs

#1772 Attempt to fix ANRs by moving some tasks during configure to background
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/identity/IdentityManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/subscriberattributes/caching/SubscriberAttributesMigrationExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/identity/IdentityManagerTests.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesDeviceCacheTests.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: fix

#1783 Updates Gradle (8.9), AGP (8.5.1) and maven.publish (0.28.0)
  examples/CustomEntitlementComputationSample/gradle/wrapper/gradle-wrapper.properties
  examples/MagicWeather/gradle/wrapper/gradle-wrapper.properties
  examples/MagicWeatherCompose/gradle/wrapper/gradle-wrapper.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#1791 [Paywalls] Fix `RemoteImage` flicker on activity changes
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
Labels: fix, RevenueCatUI

#1789 Adds pricePerPeriod functions to PricingPhase
  api-tester/src/main/java/com/revenuecat/apitester/java/PricingPhaseAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PricingPhaseAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/PricingPhase.kt
  purchases/src/test/java/com/revenuecat/purchases/common/models/ParameterizedPricingPhaseTest.kt
Labels: feat

#1795 Diagnostics: Remove unused anonymizer
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Anonymizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AnonymizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: refactor

#1796 Adds the Detekt IntelliJ plugin settings to version control.
  .gitignore
  .idea/detekt.xml
Labels: build

#1798 Adds the baseline file to the Detekt IntelliJ plugin settings.
  .idea/detekt.xml
Labels: build
