Repository RevenueCat/purchases-android, pull requests merged in 2024-06, with the labels that each got.

#1716 Set INFORMATIONAL trusted entitlements mode as the default in the purchase tester app
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
Labels: test

#1708 Deprecate observerMode in favor of purchasesAreCompletedBy
  api-tester/src/defaults/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesAreCompletedByAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesAreCompletedByAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  examples/MagicWeather/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainApplication.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  examples/purchase-tester/src/main/res/layout/fragment_configure.xml
  examples/purchase-tester/src/main/res/values/strings.xml
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesAreCompletedBy.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: refactor

#1729 Stops collecting the ANDROID_ID.
  purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcher.kt
  purchases/src/test/java/com/revenuecat/purchases/google/attribution/GoogleDeviceIdentifiersFetcherTests.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesManagerTests.kt
Labels: fix

#1717 Support pending prepaid purchases
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: feat

#1731 Adds 6.9.8 to the changelog.
  CHANGELOG.md
Labels: docs

#1727 Fixes crash if no browser is installed
  gradle/libs.versions.toml
  ui/revenuecatui/build.gradle
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/UriHandlerExtensions.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/FooterLinksNoBrowserTest.kt
Labels: fix

#1735 SDK-3477 Show a toast when a paywall link is clicked without a browser installed
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
  ui/revenuecatui/src/main/res/values-ar/strings.xml
  ui/revenuecatui/src/main/res/values-bg/strings.xml
  ui/revenuecatui/src/main/res/values-ca/strings.xml
  ui/revenuecatui/src/main/res/values-cs/strings.xml
  ui/revenuecatui/src/main/res/values-da/strings.xml
  ui/revenuecatui/src/main/res/values-de/strings.xml
  ui/revenuecatui/src/main/res/values-el/strings.xml
  ui/revenuecatui/src/main/res/values-es/strings.xml
  ui/revenuecatui/src/main/res/values-fi/strings.xml
  ui/revenuecatui/src/main/res/values-fr/strings.xml
  ui/revenuecatui/src/main/res/values-he/strings.xml
  ui/revenuecatui/src/main/res/values-hi/strings.xml
  ui/revenuecatui/src/main/res/values-hr/strings.xml
  ui/revenuecatui/src/main/res/values-hu/strings.xml
  ui/revenuecatui/src/main/res/values-id/strings.xml
  ui/revenuecatui/src/main/res/values-it/strings.xml
  ui/revenuecatui/src/main/res/values-ja/strings.xml
  ui/revenuecatui/src/main/res/values-kk/strings.xml
  ui/revenuecatui/src/main/res/values-ko/strings.xml
  ui/revenuecatui/src/main/res/values-ms/strings.xml
  ui/revenuecatui/src/main/res/values-nl/strings.xml
  ui/revenuecatui/src/main/res/values-no/strings.xml
  ui/revenuecatui/src/main/res/values-pl/strings.xml
  ui/revenuecatui/src/main/res/values-pt/strings.xml
  ui/revenuecatui/src/main/res/values-ro/strings.xml
  ui/revenuecatui/src/main/res/values-ru/strings.xml
  ui/revenuecatui/src/main/res/values-sk/strings.xml
  ui/revenuecatui/src/main/res/values-sv/strings.xml
  ui/revenuecatui/src/main/res/values-th/strings.xml
  ui/revenuecatui/src/main/res/values-tr/strings.xml
  ui/revenuecatui/src/main/res/values-uk/strings.xml
  ui/revenuecatui/src/main/res/values-vi/strings.xml
  ui/revenuecatui/src/main/res/values-zh-rHK/strings.xml
  ui/revenuecatui/src/main/res/values-zh-rTW/strings.xml
  ui/revenuecatui/src/main/res/values-zh/strings.xml
  ui/revenuecatui/src/main/res/values/strings.xml
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/FooterLinksNoBrowserTest.kt
Labels: feat

#1737 Support BC7
  README.md
  api-tester/src/defaults/java/com/revenuecat/apitester/java/DeprecatedPurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/DeprecatedPurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/GoogleProrationModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/GoogleReplacementModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/InstallmentsInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreTransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionOptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/UpgradeInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleProrationModeAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/InstallmentsInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreTransactionAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionOptionAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/UpgradeInfoAPI.kt
  build.gradle
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedOfferingFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/DeprecatedPackageCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/SubscriptionOptionExtensions.kt
  gradle/libs.versions.toml
  integration-tests/build.gradle
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/factories/StoreTransactionFactory.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/ProrationMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UpgradeInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/subscriptionOptionConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleInstallmentsInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleProrationMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleReplacementMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/InstallmentsInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/SubscriptionOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/TestStoreProduct.kt
  purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/ReceiptInfoTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/billingClientStubs.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
  test-apps/testpurchasesandroidcompatibility/build.gradle.kts
  ui/debugview/src/main/kotlin/com/revenuecat/purchases/ui/debugview/models/TestModels.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PackageExtensionsTest.kt
Labels: breaking

#1738 Add V8 Migration guide
  README.md
  migrations/v8-MIGRATION.md
Labels: docs

#1740 Improve migration guide for V8
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/ConfigureFragment.kt
  migrations/v8-MIGRATION.md
Labels: docs

#1741 Updates MockK to 1.13.11 to fix integration tests.
  gradle/libs.versions.toml
Labels: dependencies, fix

#1743 Remove `ExperimentalPreviewRevenueCatUIPurchasesAPI` annotations
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/FontProviderAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallActivityLauncherAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallFooterViewAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallResultAPI.java
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallViewAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/FontProviderAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallActivityLauncherAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallDialogOptionsAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallFooterViewAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallListenerAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallOptionsAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallResultAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallViewAPI.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainActivity.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallFooterViewActivity.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallViewActivity.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywallfooter/PaywallFooterScreen.kt
  migrations/v8-MIGRATION.md
  ui/revenuecatui/src/androidTest/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallUITest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/Paywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallListener.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallContract.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallResult.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/TypographyExtensions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/CustomFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/CustomParcelizableFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/FontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/GoogleFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/ParcelizableFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFont.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFontFamily.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallTheme.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/TypographyType.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallViewAttributesReader.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/FooterLinksNoBrowserTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/TemplateSnapshotTest.kt
Labels: breaking, feat

#1744 Bump kotlin to 1.8 in MagicWeatherCompose
  examples/MagicWeatherCompose/gradle/libs.versions.toml
Labels: build

#1745 Add retries upon Google's SERVICE_UNAVAILABLE error when app in foreground
  purchases/src/main/kotlin/com/revenuecat/purchases/common/durationExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/BillingClientUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesByTypeUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCaseTest.kt
Labels: refactor

#1746 Release/8.0.0
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  docs/index.html
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  gradle.properties
  library.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Config.kt
Labels: next_release

#1749 Remove unneeded Android Lollipop version checks
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/utils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/LocaleExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
Labels: refactor

#1750 Paywalls: Add bottom padding when there are no buttons in footer
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template1.kt
Labels: fix

#1721 Update observermode docs URLs
  examples/MagicWeather/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  examples/MagicWeatherCompose/app/src/main/java/com/revenuecat/sample/MainApplication.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesAreCompletedBy.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
Labels: docs

#1752 SDK-3482 Updates various orbs and images
  .circleci/config.yml
Labels: ci

#1666 `Amazon`: Add getAmazonLWAConsentStatus method to support Quick Subscribe
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/AmazonLWAConsentStatusAPI.kt
  examples/purchase-tester/src/main/AndroidManifest.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/AmazonLWAConsentStatus.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/DefaultPurchasingServiceProvider.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetAmazonLWAConsentStatusCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/helpers/dummies.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat

#1756 Support ISO8601-2 period durations
  api-tester/src/main/java/com/revenuecat/apitester/java/PeriodAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PeriodAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/Period.kt
  purchases/src/test/java/com/revenuecat/purchases/models/PeriodTest.kt
Labels: fix

#1757 Makes `ITEM_NOT_OWNED` message more clear when restoring and acknowledging/consuming
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/PurchaseStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
Labels: fix

#1754 Update test lane to require active entitlements
  fastlane/Fastfile
Labels: test

#1760 Change android integration test to cover more testable use case
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/offlineentitlements/OfflineEntitlementsWithInitialRequestsCompletedIntegrationTest.kt
Labels: test

#1759 Release/8.1.0
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  docs/index.html
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeather/gradle/libs.versions.toml
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  gradle.properties
  library.gradle
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Config.kt
Labels: next_release

#1762 Adds .aiexclude
  .aiexclude
Labels: feat

#1751 Add `DEFERRED` replacement mode
  api-tester/src/main/java/com/revenuecat/apitester/java/GoogleReplacementModeAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/GoogleReplacementModeAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleReplacementMode.kt
Labels: feat

#1766 Use correct product context with `DEFERRED` purchases
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: fix
