Repository RevenueCat/purchases-android, pull requests merged in 2024-03, with the labels that each got.

#1634 Fix amazon zero price
  purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
Labels: fix

#1637 [v6 HOTFIX] Fix amazon zero price (#1634)
  purchases/src/main/kotlin/com/revenuecat/purchases/PostTransactionWithProductDetailsHelper.kt
Labels: fix

#1639 Add 6.9.7 to changelog
  CHANGELOG.md
Labels: docs

#1640 Revert to previous androidx core version (1.8.0)
  gradle/libs.versions.toml
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingDelegate.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingDelegateTest.kt
Labels: refactor

#1648 Create android test apps to test Android SDK regressions
  .circleci/config.yml
  settings.gradle
  test-apps/testpurchasesandroidcompatibility/.gitignore
  test-apps/testpurchasesandroidcompatibility/build.gradle.kts
  test-apps/testpurchasesandroidcompatibility/proguard-rules.pro
  test-apps/testpurchasesandroidcompatibility/src/main/AndroidManifest.xml
  test-apps/testpurchasesandroidcompatibility/src/main/java/com/revenuecat/testpurchasesandroidcompatibility/MainActivity.kt
  test-apps/testpurchasesandroidcompatibility/src/main/res/drawable-v24/ic_launcher_foreground.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/drawable/ic_launcher_background.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/layout/activity_main.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-hdpi/ic_launcher.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-mdpi/ic_launcher.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-xhdpi/ic_launcher.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  test-apps/testpurchasesandroidcompatibility/src/main/res/values-night/themes.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/values/colors.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/values/strings.xml
  test-apps/testpurchasesandroidcompatibility/src/main/res/values/themes.xml
  test-apps/testpurchasesuiandroidcompatibility/.gitignore
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
  test-apps/testpurchasesuiandroidcompatibility/proguard-rules.pro
  test-apps/testpurchasesuiandroidcompatibility/src/main/AndroidManifest.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/java/com/revenuecat/testpurchasesuiandroidcompatibility/MainActivity.kt
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/drawable/ic_launcher_background.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/drawable/ic_launcher_foreground.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-hdpi/ic_launcher.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-mdpi/ic_launcher.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-xhdpi/ic_launcher.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/values/colors.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/values/strings.xml
  test-apps/testpurchasesuiandroidcompatibility/src/main/res/values/themes.xml
Labels: test

#1649 Correctly support RGBA colors
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallColorAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallColorAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallColorTest.kt
Labels: refactor

#1652 Add space to title in Template 5
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/UIConstant.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template5.kt
Labels: fix, RevenueCatUI

#1650 Create AssetFont
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFont.kt
Labels: feat

#1657 Add `RC_BILLING` store
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  purchases/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
Labels: refactor

#1659 Update android executor to a non-deprecated tag
  .circleci/config.yml
Labels: ci
