Repository RevenueCat/purchases-android, pull requests merged in 2024-04, with the labels that each got.

#1664 Add store entry for External Purchases API
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  purchases/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
Labels: fix

#1665 Support sending only diagnostics events and update data to raw data
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/ResponseTimeRange.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: refactor

#1660 Track Amazon events
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/ResponseTimeRange.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: feat

#1658 Create Amazon diagnostic Counters
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEventName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/ResponseTimeRange.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBillingTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsAnonymizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: feat

#1670 Remove confusing placements error log
  purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
Labels: refactor

#1674 Paywalls: Allow closed button color to be configured
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/CloseButton.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ColorsFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfiguration.kt
Labels: feat

#1676 Only update docs index on latest stable releases
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#1680 Update BillingClient version to 6.2.1
  gradle/libs.versions.toml
Labels: dependencies, feat

#1688 `Paywalls`: Update Norwegian "restore" localization
  ui/revenuecatui/src/main/res/values-no/strings.xml
Labels: fix

#1690 Checks if callback has already been called in `canMakePayments`
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/PurchaseStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCanMakePaymentsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
Labels: fix

#1684 Add new diagnostics events for diagnostics
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
Labels: refactor

#1685 Make clearing diagnostics file happen during tracking
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: refactor

#1692 Add trigger_bump lane
  fastlane/Fastfile
  fastlane/README.md
Labels: ci
