Repository RevenueCat/purchases-android, pull requests merged in 2024-09, with the labels that each got.

#1825 [Diagnostics] Send backend_error_code in http request failures if available
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/HTTPResult.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: refactor

#1832 [Paywalls] Fix previews emerge snapshots
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
Labels: test

#1834 Fixes a Paywall Template 7 crash when none of the tiers have any available products.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/MultiTierTemplateConfigurationFactoryTest.kt
Labels: pr:fix

#1831 [EXTERNAL] Add Emerge snapshot testing (#1785) by @rbro112
  .circleci/config.yml
  build.gradle
  fastlane/Fastfile
  fastlane/README.md
  gradle/libs.versions.toml
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallFooter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallDataExtensions.kt
Labels: pr:test

#1829 Add `$kochavaDeviceId` attribution convencience method
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: pr:feat

#1838 Revert "Add `$kochavaDeviceId` attribution convencience method (#1829)"
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/subscriberattributes/SpecialSubscriberAttributes.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: pr:refactor

#1845 Bump fastlane-plugin-revenuecat_internal from `5140dbc` to `55a0455`
  Gemfile.lock
Labels: pr:other

#1843 [EXTERNAL] Wireup Emerge gradle plugin config for PR snapshot diffs (#1841) by @rbro112
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PaywallIcon.kt
Labels: pr:other

#1846 Fix crash if activity finished while calculating presentation logic
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
Labels: pr:fix, pr:RevenueCatUI

#1850 Fix interaction not disabled during purchases
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
Labels: pr:fix, pr:RevenueCatUI

#1851 Converts MagicWeatherCompose's Gradle files to Kotlin
  examples/MagicWeatherCompose/app/build.gradle
  examples/MagicWeatherCompose/app/build.gradle.kts
  examples/MagicWeatherCompose/app/proguard-rules.pro
  examples/MagicWeatherCompose/build.gradle.kts
  examples/MagicWeatherCompose/settings.gradle
  examples/MagicWeatherCompose/settings.gradle.kts
Labels: pr:other

#1852 Converts CustomEntitlementComputationSample's Gradle files to Kotlin
  examples/CustomEntitlementComputationSample/app/build.gradle
  examples/CustomEntitlementComputationSample/app/build.gradle.kts
  examples/CustomEntitlementComputationSample/app/proguard-rules.pro
  examples/CustomEntitlementComputationSample/build.gradle.kts
  examples/CustomEntitlementComputationSample/settings.gradle.kts
Labels: pr:other

#1853 Adds some more test cases validating {{ total_price_and_per_month }} for quarterly packages.
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Labels: pr:other

#1854 Fix multiple paywalls display issues
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
Labels: pr:fix
