Repository RevenueCat/purchases-android, pull requests merged in 2024-02, with the labels that each got.

#1590 Add missing forwarding to `PaywallListener.onPurchaseCancelled`
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
Labels: fix

#1589 [EXTERNAL] Exposing fontprovider setter in `PaywallView` and `PaywallFooterView` by @Jjastiny
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallFooterViewAPI.kt
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallViewAPI.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
Labels: feat

#1593 Fix `DEFERRED` purchases when passing old product id in invalid format
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: fix

#1596 Update CHANGELOG with 6.9.6 release notes
  CHANGELOG.md
Labels: docs

#1599 `Paywalls`: add 4 new variables
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableDataProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PeriodExtensions.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorTest.kt
Labels: RevenueCatUI

#1598 Revert making PaywallFooterView an AbstractComposeView
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallFooterViewAPI.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallFooterView.kt
Labels: fix

#1601 Catch Exception instead of only IllegalArgumentException when decoding paywallData
  purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
Labels: fix

#1600 `Paywalls`: add test coverage for locales with different region
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/LocaleExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/LocaleExtensionsTest.kt
Labels: test

#1605 Fix paywall POST receipt data for paywall revision
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/events/PaywallPostReceiptData.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
Labels: fix, refactor

#1606 Fix serialization proguard rules
  purchases/consumer-rules.pro
Labels: fix

#1610 Paywalls: Call `PaywallDialog` dismiss handler after successful restore if needed
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelFactory.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Labels: fix, RevenueCatUI

#1616 [External] Update russian and kazakh translations (#1577 by @janbolat)
  ui/revenuecatui/src/main/res/values-kk/strings.xml
  ui/revenuecatui/src/main/res/values-ru/strings.xml
Labels: refactor

#1613 Fix safe insets on full screen
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallViewActivity.kt
  fastlane/.purchases-android-snapshots-commit
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/CloseButton.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Footer.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/InsetSpacers.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template2.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template4.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
Labels: fix

#1617 Paywalls: No-op on all view model methods in the Loading paywall screen
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/LoadingPaywall.kt
Labels: fix

#1618 Fix load shedder integration tests
  purchases/src/androidTestCustomEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: test

#1622 Fix runtime crash when using amazon and targetting android 14
  gradle/libs.versions.toml
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingDelegate.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/purchasing/ProxyAmazonBillingDelegateTest.kt
Labels: fix

#1623 Change default paywall background with a lower quality image
  ui/revenuecatui/src/main/res/drawable/default_background.jpg
Labels: refactor

#1604 Add `getCurrentOffering(forPlacement: String)` to `Offerings`
  api-tester/src/main/java/com/revenuecat/apitester/java/OfferingsAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/PresentedOfferingContextAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingsAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PresentedOfferingContextAPI.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallTesterApp.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/AppScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/MainScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreenViewModel.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  examples/purchase-tester/src/main/res/values/strings.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/Offerings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PresentedOfferingContext.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONArrayExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Labels: feat

#1628 Add targeting to `PresentedOfferingContext`
  api-tester/src/main/java/com/revenuecat/apitester/java/PresentedOfferingContextAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/StoreProductAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PresentedOfferingContextAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/StoreProductAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Offerings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PresentedOfferingContext.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/JSONObjectExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: feat

#1626 New `syncAttributesAndOfferingsIfNeeded` method
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingCardAdapter.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  examples/purchase-tester/src/main/res/layout/dialog_set_attribute.xml
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/SyncAttributesAndOfferingsCallback.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/SyncAttributesAndOfferingsStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/RateLimiter.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/RateLimiterTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: feat
