Repository RevenueCat/purchases-android, pull requests merged in 2025-03, with the labels that each got.

#2204 chore: Delete key from customer center survey event
  purchases/src/main/kotlin/com/revenuecat/purchases/common/events/BackendEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/events/BackendStoredEvent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/events/CustomerCenterSurveyOptionChosenEvent.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendEventsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/events/EventsManagerTest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
Labels: pr:other, feat:Customer Center

#2208 [Paywalls V2] Some more template previews optimizations
  ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
Labels: pr:other

#2209 [Paywalls V2] Ignores template previews for now.
  ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
Labels: pr:other

#2206 Logs from RevenueCatUI are now tagged with `[Purchases]` too.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/Logger.kt
Labels: pr:other

#2201 Adds a `LocalPreviewImageLoader` `CompositionLocal`.
  config/detekt/detekt.yml
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
Labels: pr:other

#2212 Add `hasPaywall` property to `Offering`
  api-tester/src/main/java/com/revenuecat/apitester/java/OfferingAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/OfferingAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
Labels: pr:feat

#2202 Fixes CustomerCenter state not refreshing when reopening
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2213 Adds support for switching between 2 API keys to PaywallsTester
  .circleci/config.yml
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ConfigurePurchasesUseCase.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/Constants.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainApplication.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreenViewModel.kt
Labels: pr:RevenueCatUI, pr:other

#2203 Reload Customer Center after a successful restore
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/dialogs/RestorePurchasesDialog.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2199 Create `CustomerCenterListener`
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainApplication.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
  purchases/build.gradle
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterListener.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModelFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#2217 [EXTERNAL] Bump Emerge Gradle Plugin and Snaphsots version (#2211) via @runningcode
  gradle/libs.versions.toml
Labels: pr:other

#2221 Fixes inconsistent package ordering on tiered paywalls (template 7)
  fastlane/.purchases-android-snapshots-commit
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/PackageConfigurationFactory.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/MultiTierTemplateConfigurationFactoryTest.kt
Labels: pr:fix, pr:RevenueCatUI

#2222 Prevent Paywalls V1 Template 7 from defaulting empty badge to showing percent off
  fastlane/.purchases-android-snapshots-commit
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/ProcessedLocalizedConfiguration.kt
Labels: pr:fix, pr:RevenueCatUI

#2225 Fix `CustomerCenterActivity` colors on dark mode
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterActivity.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2227 Set default interfaces compiler flag to `all-compatibility`
  purchases/build.gradle
Labels: pr:fix

#2229 fix: Remove API dependency with Coil
  integration-tests/proguard-rules.pro
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PurchasesExtensions.kt
Labels: pr:fix

#2230 [Paywalls V2] Fixes locales without region and `X-Preferred-Locales`
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/FakeLocaleProvider.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/LocaleIdTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2219 [Paywalls V2] Disable all buttons when any action is in progress
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2234 [Paywalls V2] Handles potential locale id inconsistency between strings and variables
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2210 Virtual Currency Balances
  api-tester/src/main/java/com/revenuecat/apitester/java/CustomerInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/VirtualCurrencyInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/CustomerInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VirtualCurrencyInfoAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/VirtualCurrencyInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/CustomerInfoResponseJsonKeys.kt
  purchases/src/test/java/com/revenuecat/purchases/ParcelableTests.kt
  purchases/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt
Labels: pr:feat, feat:Virtual Currency

#2235 [Paywalls V2] Avoids the theme from influencing the text color
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2236 Fix background painting outside composable
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Background.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2238 [Paywalls V2] Reorganizes stack arrangement logic
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/HorizontalStack.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/VerticalStack.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2245 [Paywalls V2] Considers script when matching locales
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/LocaleIdTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2244 Add refresh button to PaywallTester app
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsViewModel.kt
Labels: pr:other

#2247 [Paywalls V2] Refactors `StyleFactory`
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2251 Update fastlane plugin
  Gemfile.lock
Labels: pr:other

#2253 [Paywalls V2] Timeline component fixes
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2255 [EXTERNAL] Set metaspace size to avoid "Daemon disappeared" failures (#2237) contributed by @runningcode
  gradle.properties
Labels: pr:other

#2252 [Paywalls V2] Avoids re-parsing the component tree to find packages and tabs
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/NonEmptyList.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/pkg/PackageComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewWindowTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewVariablesTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewWindowTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2256 [Paywalls V2] Tweaks the `MissingPackage` error message.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2260 Allows configuring `showInAppMessagesAutomatically` and `pendingTransactionsForPrepaidPlansEnabled` in customEntitlementComputation mode
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/customEntitlementComputation/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/PurchasesConfigurationForCustomEntitlementsComputationMode.kt
Labels: pr:other, pr:force_patch

#2232 Uploads Paparazzi screenshots to Emerge.
  .circleci/config.yml
  fastlane/.purchases-android-snapshots-commit
  fastlane/Fastfile
  ui/revenuecatui/src/test/snapshots/images/.gitkeep
Labels: pr:other

#2265 Fix landscape mode in Paywalls v1 Template 3
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/templates/Template3.kt
Labels: pr:fix, pr:RevenueCatUI

#2266 [Paywalls V2] Fixes badges not being overriden
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedStackPartial.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/BadgeStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedStackPartialTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2268 [Diagnostics] Add `id` and `app_session_id` to events
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntry.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerFunctionalTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2270 Add `onManagementOptionSelected` to `CustomerCenterListener`
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
  purchases/src/main/java/com/revenuecat/purchases/customercenter/CustomerCenterManagementOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterListener.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#2271 [Paywalls V2] Ignores missing font alias if it's blank.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LocalizedTextPartial.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/FontSpec.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/Result.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2170 feat: Introduce `CustomerCenterView` for hybrid usage
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/CustomerCenterView.kt
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#2274 [Diagnostics] add `no_entitlement_mapping_available` reason to error_entering_offline_entitlements_mode` event
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2267 [Diagnostics] Tracks BillingClient connected/disconnected events.
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesByTypeUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCaseTest.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2277 [Paywalls V2] Avoids adding spurious digits to per-period prices
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewVariablesTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2276 [Diagnostics] add `is_retry` to `http_request_performed` event
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2279 [Diagnostics] Add google purchase started and update received events
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
Labels: pr:other

#2280 [Diagnostics] add `GET_OFFERINGS_STARTED` and `GET_OFFERINGS_RESULT` events
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsResultData.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
Labels: pr:other

#2283 [Diagnostics] add GET_PRODUCTS_STARTED and GET_PRODUCTS_RESULT events
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: pr:other

#2285 [Diagnostics] Add `amazon_purchase_attempt` event
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/handler/PurchaseHandler.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/handler/PurchaseHandlerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2286 [Diagnostics] Add sync purchases started and result events
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/SyncPurchasesHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2287 [Paywalls V2] Fuzzy-matches language without region
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2289 [Diagnostics] add GET_CUSTOMER_INFO_STARTED and GET_CUSTOMER_INFO_RESULT events
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfoHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PostPendingTransactionsHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/EntitlementInfoHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PostPendingTransactionsHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/SyncPurchasesHelperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesCoroutinesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: pr:other

#2291 [Diagnostics] add `PURCHASE_STARTED` and `PURCHASE_RESULT` events
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/productStubs.kt
Labels: pr:other

#2294 [Diagnostics] Add Google event missing properties
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchasesByTypeUseCase.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesByTypeUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchasesUseCaseTest.kt
Labels: pr:other

#2296 Wrap Billing client crash with ours with more information
  api-tester/src/main/java/com/revenuecat/apitester/java/NoCoreLibraryDesugaringExceptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/NoCoreLibraryDesugaringExceptionAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/NoCoreLibraryDesugaringException.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
Labels: pr:other

#2304 [Diagnostics] Sync diagnostics if file reaches lower limit
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsFileHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2305 [Paywalls V2] Fixes the update-paywall-templates job
  fastlane/Fastfile
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2308 Fix load shedder backend integration tests
  fastlane/README.md
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/LoadShedderBackendIntegrationTest.kt
Labels: pr:other

#2310 Remove redundant kotlin stdlib dependencies
  examples/MagicWeather/app/build.gradle.kts
  examples/purchase-tester/build.gradle
  gradle/libs.versions.toml
  integration-tests/build.gradle
  purchases/build.gradle
Labels: pr:dependencies

#2309 Attempts to have Emerge Snapshots handle merge queue branches.
  .circleci/config.yml
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
Labels: pr:other
