Repository RevenueCat/purchases-android, pull requests merged in 2025-07, with the labels that each got.

#2473 Use subscription's managementURL instead of CustomerInfo's in Customer Center
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformation.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
Labels: pr:fix

#2475 Update workflows/issue-notifications.yml@v2
  .github/workflows/issue-notifications.yml
Labels: pr:other

#2459 Use Material TopAppBar in Customer Center
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterConstants.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/navigation/CustomerCenterDestination.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/navigation/CustomerCenterNavigationState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsButtonsView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/RelevantPurchasesListView.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/navigation/CustomerCenterNavigationStateTest.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2476 Migrates publishing to Maven Central Portal.
  .circleci/config.yml
  bom/build.gradle.kts
  fastlane/Fastfile
  gradle.properties
  gradle/libs.versions.toml
Labels: pr:other

#2477 BC8 migration
  api-tester/src/main/java/com/revenuecat/apitester/java/NoCoreLibraryDesugaringExceptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/NoCoreLibraryDesugaringExceptionAPI.kt
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/NotFinishingTransactionsBillingClient.kt
  gradle/libs.versions.toml
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/NoCoreLibraryDesugaringException.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/purchaseHistoryRecordExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/billingResultExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/storeTransactionConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCanMakePaymentsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/billingClientStubs.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: pr:breaking, pr:other

#2491 CEC Mode Purchases Constructor w/ VCManager
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
Labels: pr:other

#2478 Improve Composable stabilities
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/carousel/CarouselComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BorderStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/ShadowStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModel.kt
Labels: pr:RevenueCatUI, pr:other

#2488 Use collectAsStateWithLifecycle instead of collectAsState in Compose
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywall/PaywallScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/paywallfooter/PaywallFooterScreen.kt
  ui/debugview/src/debug/kotlin/com/revenuecat/purchases/ui/debugview/InternalDebugRevenueCatScreen.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
Labels: pr:RevenueCatUI, pr:other

#2494 Move VirtualCurrencyManager to PurchasesOrchestrator
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
Labels: pr:other

#2489 Add codelab instructions on README file
  README.md
Labels: pr:other

#2506 BC8 migration
  api-tester/src/main/java/com/revenuecat/apitester/java/NoCoreLibraryDesugaringExceptionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/NoCoreLibraryDesugaringExceptionAPI.kt
  config/detekt/detekt-baseline.xml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/NotFinishingTransactionsBillingClient.kt
  gradle/libs.versions.toml
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/NoCoreLibraryDesugaringException.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonBilling.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BillingAbstract.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsEntryName.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/purchaseHistoryRecordExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/BillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/billingResultExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/storeTransactionConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/BillingStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/OfferingStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCanMakePaymentsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculatorTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/BillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/AcknowledgePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/BaseBillingUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/ConsumePurchaseUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryProductDetailsUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/google/usecase/QueryPurchaseHistoryUseCaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/billingClientStubs.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: pr:breaking, pr:other

#2498 Removes data classes from public API
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  build.gradle.kts
  config/detekt/detekt.yml
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OfferingFragment.kt
  gradle/libs.versions.toml
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/data/LogInResult.kt
  purchases/src/main/java/com/revenuecat/purchases/customercenter/CustomerCenterManagementOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CustomerInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/DangerousSettings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Offering.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Offerings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/Package.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PresentedOfferingContext.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseParams.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchaseResult.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonPurchasingData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/amazon/AmazonStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/PlatformInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/events/EventsRequest.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/RedeemWebPurchaseListener.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleInstallmentsInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GooglePurchasingData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/GoogleSubscriptionOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/Period.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/Price.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/PricingPhase.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/StoreTransaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/TestStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/Transaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallColor.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/PaywallData.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCoroutinesCommonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  ui/revenuecatui/api.txt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialogOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PurchaseLogic.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallResult.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessor.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/GoogleFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFont.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFontFamily.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/LegacyPaywallDataValidationTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewVariablesTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/Offering.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/Package.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/PaywallData.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/extensions/TestStoreProduct.kt
Labels: pr:breaking, pr:other, codex

#2512 Fixes compilation of the CEC sample app.
  examples/CustomEntitlementComputationSample/app/src/main/java/com/revenuecat/sample/main/MainViewModel.kt
Labels: pr:other

#2440 Bump AGP to 8.10.1 and Gradle to 8.14.2
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#2496 Fetch VCs from Network
  examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewViewModel.kt
  examples/purchase-tester/src/main/res/layout/fragment_overview.xml
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/VirtualCurrencyStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrenciesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrencyFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrencyManager.kt
  purchases/src/test/java/com/revenuecat/purchases/common/DeviceCacheTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
  purchases/src/test/java/com/revenuecat/purchases/virtualcurrencies/VirtualCurrenciesFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/virtualcurrencies/VirtualCurrencyFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/virtualcurrencies/VirtualCurrencyManagerTest.kt
Labels: pr:other, feat:Virtual Currency

#2505 Add VC integration tests
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionVirtualCurrenciesIntegrationTest.kt
Labels: pr:other, feat:Virtual Currency

#2522 Add CLAUDE.md
  CLAUDE.md
Labels: pr:other

#2520 Make PaywallActivity not consume insets in Android 16+
  .circleci/config.yml
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2527 Introduces `CompatComposeView` to handle scenarios where the view tree is not set up
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/CompatComposeView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/CustomerCenterView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/OriginalTemplatePaywallFooterView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
Labels: pr:other

#2538 Dont run VC tests on load shedder integration tests
  fastlane/Fastfile
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/Constants.kt
  purchases/src/androidTestDefaults/kotlin/com/revenuecat/purchases/PurchasesIntegrationTest.kt
Labels: pr:other

#2542 Expose API key validation result to BillingFactory
  purchases/src/main/kotlin/com/revenuecat/purchases/APIKeyValidator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/ConfigureStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/APIKeyValidatorTest.kt
  purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
Labels: pr:other

#2543 Expose Virtual Currency Constructors with @InternalRevenueCatAPI
  api-tester/src/main/java/com/revenuecat/apitester/java/VirtualCurrenciesAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/VirtualCurrencyAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VirtualCurrenciesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VirtualCurrencyAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/InternalRevenueCatAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrencies.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/virtualcurrencies/VirtualCurrency.kt
Labels: pr:feat

#2487 Resubscribe if cancelled
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix

#2552 Update VC Caching Log Message
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/VirtualCurrencyStrings.kt
Labels: pr:fix, feat:Virtual Currency

#2559 Update design of No Active subscriptions screen in Customer Center
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterUIConstants.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/theme/CustomerCenterPreviewTheme.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/NoActiveUserManagementView.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2549 Parallel test jobs
  .circleci/config.yml
Labels: pr:other

#2564 Display latest expired subscription if no active subscriptions
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2573 Convert WebBilling products into TestStoreProducts
  api-tester/src/main/java/com/revenuecat/apitester/java/TestStoreProductAPI.java
  purchases/src/main/kotlin/com/revenuecat/purchases/models/TestStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStoreProductConverter.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStorePurchasingData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/teststore/TestStoreProductConverterTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/PriceFactoryTest.kt
Labels: pr:other

#2565 Add lifetime badge to customer center
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterConstants.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterConfigTestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformation.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PurchaseInformationCardView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PurchaseStatusBadge.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PurchaseInformationCardViewTest.kt
Labels: pr:fix

#2572 Introduce custom actions for customer center
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainApplication.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
  purchases/src/main/java/com/revenuecat/purchases/customercenter/CustomerCenterManagementOption.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomActionData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterListener.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/actions/CustomerCenterAction.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PathUtils.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomActionDataTest.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:feat, feat:Customer Center

#2575 Add support for az-AZ locale
  ui/revenuecatui/src/main/res/values-az/strings.xml
Labels: pr:feat, pr:RevenueCatUI
