Repository RevenueCat/purchases-android, pull requests merged in 2025-04, with the labels that each got.

#2313 Migrate purchases Gradle module to KTS
  config/detekt/detekt-baseline.xml
  purchases/build.gradle
  purchases/build.gradle.kts
Labels: pr:other

#2311 [Paywalls V2] Renders images in template previews
  ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
  ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/ImagePreviews.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/HelperFunctions.kt
  ui/revenuecatui/src/release/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/ImagePreviews.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2319 Improve Korean translation
  ui/revenuecatui/src/main/res/values-ko/strings.xml
Labels: pr:other

#2317 Reload customer center after successful promo
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2298 feat: Change default copy for web_subscription_manage #4921
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#2320 [Paywalls v2] Supports custom fonts in `assets/fonts`
  examples/paywall-tester/src/main/assets/fonts/Bytesized-Regular.ttf
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/SamplePaywalls.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/FontSpec.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/PaywallResourceProvider.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallComponentDataValidationTests.kt
Labels: pr:feat, pr:RevenueCatUI, feat:PaywallV2

#2318 Clean up libs.versions.toml
  gradle/libs.versions.toml
Labels: pr:other

#2321 Add `X-Is-Backgrounded` header to all requests
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesLifecycleTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
Labels: pr:other

#2323 Migrate Groovy to KTS for purchases-ui module
  ui/revenuecatui/build.gradle
  ui/revenuecatui/build.gradle.kts
  ui/revenuecatui/lint.xml
  ui/revenuecatui/proguard-rules.pro
Labels: pr:other

#2326 [Paywalls v2] Ignores already-consumed window insets.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2325 fix: Check eligible for promo offers
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix, feat:Customer Center

#2316 Clean up on restoring functionality in customer center
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendGetCustomerCenterConfigTest.kt
  purchases/src/test/resources/get_customer_center_config_success.json
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/dialogs/RestorePurchasesDialog.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/dialogs/RestorePurchasesState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2328 Migrate settings.gradle to KTS and add the dependency resolutions
  build.gradle
  examples/purchase-tester/build.gradle
  settings.gradle
  settings.gradle.kts
Labels: dependencies

#2128 Add missing response fields to `CustomerInfo`. Including transaction Prices
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/java/TransactionAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionInfoAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/TransactionAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/JsonTools.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/SubscriptionInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Constants.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/CustomerInfoFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/OfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/SubscriptionInfoResponse.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/Transaction.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PriceExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/UiConfigTests.kt
  purchases/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/PaywallDataTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/CarouselComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/FallbackComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/IconComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ImageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PackageComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StackComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StickyFooterComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TabsComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TextComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TimelineComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/BackgroundTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentOverridesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentsConfigTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/LocalizationDataTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/PaywallComponentsDataTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/VariableLocalizationKeyTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/AlignmentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/BadgeStyleTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/BorderTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ColorInfoTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/CornerRadiusesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/DimensionTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FitModeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FlexDistributionTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FontTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ImageUrlsTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/MaskShapeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/PaddingTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ShadowTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ShapeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/SizeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventSerializationTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/events/PaywallEventsRequestSerializationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallViewModelTest.kt
Labels: pr:fix

#2329 [Paywalls V2] Norwegian Bokmål and Norwegian Nynorsk fall back to Norwegian.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2337 [Paywalls v2] Fixes `update-paywall-preview-resources-submodule` CI job
  .circleci/config.yml
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2339 Introduce purchases-bom package
  bom/build.gradle.kts
  bom/gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: pr:other

#2340 Migrate tester modules to KTS format
  api-tester/build.gradle
  api-tester/build.gradle.kts
  api-tester/proguard-rules.pro
  examples/paywall-tester/build.gradle
  examples/paywall-tester/build.gradle.kts
  examples/paywall-tester/proguard-rules.pro
  examples/purchase-tester/build.gradle
  examples/purchase-tester/build.gradle.kts
  examples/purchase-tester/proguard-rules.pro
Labels: pr:other

#2332 Use int for VC Balance
  api-tester/src/main/java/com/revenuecat/apitester/java/VirtualCurrencyInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/VirtualCurrencyInfoAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/VirtualCurrencyInfo.kt
Labels: pr:other, feat:Virtual Currency

#2343 Migrate root gradle file to KTS
  build.gradle
  build.gradle.kts
Labels: pr:other

#2214 [Paywalls V2] Renders template previews in a fixed resolution using Paparazzi
  .circleci/config.yml
  ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PreviewHelpers.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/PaywallValidationResult.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
  ui/revenuecatui/src/testDebug/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/PaywallComponentsTemplatePreviewRecorder.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2345 Adds `EnumDeserializerWithDefault` and `SealedDeserializerWithDefault`
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/EnumDeserializerWithDefault.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/SealedDeserializerWithDefault.kt
Labels: pr:other

#2346 [Paywalls v2] Adds a default case to most enums and sealed types
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/CarouselComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TimelineComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/ComponentOverride.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Alignment.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Badge.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/FitMode.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/FlexDistribution.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Font.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/CarouselComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/StackComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TimelineComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentOverridesTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/AlignmentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/BadgeStyleTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FitModeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FlexDistributionTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/FontTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/MaskShapeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/ShapeTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/properties/SizeTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2352 [Paywalls v2] Improves `PaywallComponentsTemplatePreviewRecorder` stability
  ui/revenuecatui/src/testDebug/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/PaywallComponentsTemplatePreviewRecorder.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2347 [Paywalls v2] Adds a default case to `Background` and `ButtonComponent`
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Background.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/OfferingImagePreDownloader.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ButtonComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/BackgroundTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentsConfigTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2351 [Paywalls v2] Uses a fixed date for template previews to avoid daily changes.
  ui/revenuecatui/src/debug/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TemplatePreviews.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2350 [Paywalls v2] Adds the unsupported Background type to the error message
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Background.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/SealedDeserializerWithDefault.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/BackgroundTests.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/common/ComponentsConfigTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2355 [Paywalls V2] Improves fuzzy matching locale when the region doesn't match
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2354 [Paywalls v2] Fixes timeline layout when width is Fit
  config/detekt/detekt.yml
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/timeline/TimelineComponentView.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2361 Add async storefront country code apis
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/interfaces/GetStorefrontCallback.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: pr:feat

#2364 Product name truncation issue in Customer Center on Android
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/SubscriptionDetailsView.kt
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#2363 Remove redundant Kotlin bom dependencies
  examples/CustomEntitlementComputationSample/app/build.gradle.kts
  examples/CustomEntitlementComputationSample/gradle/libs.versions.toml
  examples/MagicWeatherCompose/app/build.gradle.kts
  examples/MagicWeatherCompose/gradle/libs.versions.toml
  gradle/libs.versions.toml
  test-apps/testpurchasesandroidcompatibility/build.gradle.kts
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
  ui/debugview/build.gradle
Labels: pr:other

#2365 [Paywalls v2] Records and pushes template screenshots to paywall-rendering-validation
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
  ui/revenuecatui/src/testDebug/kotlin/com/revenuecat/purchases/ui/revenuecatui/snapshottests/PaywallComponentsTemplatePreviewRecorder.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2348 Adjusts precision of some Emerge Snapshots
  gradle/libs.versions.toml
  ui/revenuecatui/consumer-rules.pro
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
Labels: pr:other

#2258 [Paywalls V2] Avoids re-parsing the component tree to handle window insets
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2372 [Paywalls v2] Supports purchase buttons inside packages
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallAction.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/pkg/PackageComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/PackageComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallActionTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/pkg/PackageComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2358 Add Purchases Coroutine extensions for Result
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
Labels: pr:other

#2370 Introduce Metalava for tracking the public API surfaces
  .circleci/config.yml
  build.gradle.kts
  gradle/libs.versions.toml
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/build.gradle.kts
  purchases/src/test/java/com/revenuecat/purchases/common/events/CustomerCenterConfigDataTests.kt
  ui/revenuecatui/api.txt
  ui/revenuecatui/build.gradle.kts
Labels: pr:other, danger-bypass-size-limit

#2375 Fixes a typo: matalava -> metalava.
  .circleci/config.yml
Labels: pr:other

#2377 [EXTERNAL] fix: Optional property deserialisation error (#2376) by @thomas-coldwell
  purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/SubscriptionInfoResponse.kt
Labels: pr:fix

#2077 Handles configuring while the device is locked
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesConfiguration.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/utils.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesConfigurationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
Labels: pr:fix

#2368 Use fallback API hosts when receiving server down response
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/BackendHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/NetworkStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonBackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/BaseBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendGetCustomerCenterConfigTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendPaywallEventTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendRedeemWebPurchaseTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/subscriberattributes/SubscriberAttributesBackendTests.kt
Labels: pr:other

#2380 [Paywalls v2] Avoid image cropping when combining single-sided margin with Fixed size constraint
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2369 [Diagnostics] add host parameter to http_request_performed event
  purchases/src/main/kotlin/com/revenuecat/purchases/common/HTTPClient.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsTracker.kt
  purchases/src/test/java/com/revenuecat/purchases/common/HTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
Labels: pr:other

#2378 Update pre-commit hooks rule for checking metalava
  scripts/pre-commit.sh
Labels: pr:other

#2386 Fixes pre-commit script
  scripts/pre-commit.sh
Labels: pr:other
