Repository RevenueCat/purchases-android, pull requests merged in 2025-10, with the labels that each got.

#2577 Adds new tab ID properties to `TabsComponent`.
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/paywalls/TabsWithButtons.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/paywalls/TabsWithToggle.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TabsComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/TabsComponentTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactoryTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentViewTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2701 Revert kotlinCompilerExtensionVersion for MagicWeatherCompose and CustomEntitlementComputationSample
  examples/CustomEntitlementComputationSample/app/build.gradle.kts
  examples/MagicWeatherCompose/app/build.gradle.kts
Labels: pr:other

#2680 Paywalls -> Video Component
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/build.gradle.kts
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/utils.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/VideoComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/common/Localization.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/storage/DefaultFileRepository.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/storage/KeyedDeferredValueStore.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/OfferingImagePreDownloader.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/OfferingVideoPredownloader.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PaywallComponentFilterExtension.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/VideoComponentTests.kt
  purchases/src/test/java/com/revenuecat/purchases/storage/FileRepositoryTest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PresentedVideoPartial.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/stack/StackComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/VideoComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/video/VideoComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/video/VideoComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/video/VideoView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/errors/PaywallValidationError.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/strings/PaywallValidationErrorStrings.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabsComponentViewTests.kt
Labels: pr:RevenueCatUI, pr:other

#2707 Fix deadlock in `allowSharingPlayStoreAccount`
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
Labels: pr:fix

#2715 Add E2E Test app for integration tests
  settings.gradle.kts
  test-apps/e2etests/.gitignore
  test-apps/e2etests/build.gradle.kts
  test-apps/e2etests/proguard-rules.pro
  test-apps/e2etests/src/main/AndroidManifest.xml
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/E2ETestsApplication.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/MainActivity.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/main/CustomerInfoPage.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/main/MainPage.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/main/OfferingScreen.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/main/OfferingsPage.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/main/PackageScreen.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/ui/theme/Color.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/ui/theme/Theme.kt
  test-apps/e2etests/src/main/java/com/revenuecat/e2etests/ui/theme/Type.kt
  test-apps/e2etests/src/main/res/drawable/ic_launcher_background.xml
  test-apps/e2etests/src/main/res/drawable/ic_launcher_foreground.xml
  test-apps/e2etests/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  test-apps/e2etests/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  test-apps/e2etests/src/main/res/mipmap-hdpi/ic_launcher.webp
  test-apps/e2etests/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  test-apps/e2etests/src/main/res/mipmap-mdpi/ic_launcher.webp
  test-apps/e2etests/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  test-apps/e2etests/src/main/res/mipmap-xhdpi/ic_launcher.webp
  test-apps/e2etests/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  test-apps/e2etests/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  test-apps/e2etests/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  test-apps/e2etests/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  test-apps/e2etests/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  test-apps/e2etests/src/main/res/values/colors.xml
  test-apps/e2etests/src/main/res/values/strings.xml
  test-apps/e2etests/src/main/res/values/themes.xml
Labels: pr:other
