Repository RevenueCat/purchases-android, pull requests merged in 2025-06, with the labels that each got.

#2353 Add Paddle Store Type
  api-tester/src/main/java/com/revenuecat/apitester/java/EntitlementInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/EntitlementInfoAPI.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/EntitlementInfoFactories.kt
  purchases/src/test/java/com/revenuecat/purchases/common/EntitlementInfosTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformation.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
Labels: pr:feat

#2415 Fix display of wrong product information when not using entitlements
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
Labels: pr:fix

#2395 Update Java in .sdkmanrc to 21.0.6
  .sdkmanrc
  dokka-hide-internal/build.gradle.kts
Labels: pr:other

#2414 [Paywalls V2] Downloadable fonts
  purchases/src/defaults/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/UiConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/DownloadedFontFamily.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/FontLoader.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/OfferingFontPreDownloader.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Font.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/fonts/DownloadableFontInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/UrlConnectionFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/UiConfigTests.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/FontLoaderTest.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/OfferingFontPreDownloaderTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/TestUrlConnectionFactory.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesConfigureTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/FontSpec.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/testdata/TestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/PaywallResourceProvider.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2421 [Paywalls] Fix Bold text in Markdown on higher Weights Text composables
  config/detekt/detekt-baseline.xml
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Markdown.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2438 `getOfferings()` returns fresh Offerings and Products when the locale has changed
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsCache.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offerings/OfferingsManager.kt
  purchases/src/test/java/com/revenuecat/purchases/common/FakeLocaleProvider.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsCacheTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/offerings/OfferingsManagerTest.kt
Labels: pr:fix

#2436 [Paywalls] Buttons can now open sheets
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/InternalPaywall.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LoadedPaywallComponents.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallAction.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/SimpleBottomSheetScaffold.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/PaywallActionTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentViewTests.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2441 [Paywalls] Ensures bottom window insets are applied to the sheet.
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2442 Some Metalava updates
  .run/apiCheck.run.xml
  .run/apiDump.run.xml
  scripts/pre-commit.sh
Labels: pr:other

#2449 Support spaces in template IDs when recording Paywall screenshots
  fastlane/Fastfile
Labels: pr:other

#2437 Introduce Baseline Profiles for increasing SDK startup performance
  .gitignore
  baselineprofile/.gitignore
  baselineprofile/build.gradle.kts
  baselineprofile/src/main/AndroidManifest.xml
  baselineprofile/src/main/kotlin/com/revenuecat/baselineprofile/BaselineProfileGenerator.kt
  baselineprofile/src/main/kotlin/com/revenuecat/baselineprofile/Constants.kt
  baselineprofile/src/main/kotlin/com/revenuecat/baselineprofile/PaywallTesterScenario.kt
  baselineprofile/src/main/kotlin/com/revenuecat/baselineprofile/StartupBenchmarks.kt
  build.gradle.kts
  examples/paywall-tester/build.gradle.kts
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/MainActivity.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  purchases/build.gradle.kts
  purchases/src/main/baseline-prof.txt
  settings.gradle.kts
  ui/revenuecatui/build.gradle.kts
  ui/revenuecatui/src/main/baseline-prof.txt
Labels: pr:other, danger-bypass-size-limit

#2453 [Paywalls] Tab toggle supports gradient colors
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/modifier/Border.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/tabs/TabControlToggleView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/Switch.kt
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#2430 Redo Customer Center subscription card and action buttons
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/CustomerCenterConstants.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/SubscriptionDetailsView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/composables/SettingsButton.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterConfigTestData.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformation.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/theme/CustomerCenterPreviewTheme.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsButtonsView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/ManageSubscriptionsView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PurchaseInformationCardView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PurchaseStatusBadge.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/PurchaseInformationTest.kt
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#2451 [Paywalls] Ignores `sheet.background` property in schema
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/ButtonComponentTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/LoadedPaywallComponents.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/iconcomponent/IconComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/image/ImageComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
Labels: pr:other

#2467 Add GitHub Issue Action Ack
  .github/workflows/issue-notifications.yml
Labels: pr:other

#2468 Add `managementURL` to `SubscriptionInfo`
  api-tester/src/main/java/com/revenuecat/apitester/java/SubscriptionInfoAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/SubscriptionInfoAPI.kt
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/main/kotlin/com/revenuecat/purchases/SubscriptionInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/offlineentitlements/OfflineCustomerInfoCalculator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/CustomerInfoResponseJsonKeys.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/responses/SubscriptionInfoResponse.kt
  purchases/src/test/java/com/revenuecat/purchases/common/CustomerInfoTest.kt
  purchases/src/test/java/com/revenuecat/purchases/utils/Responses.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:feat

#2471 Issue when loading promotional offers when products are missing base plans
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PurchasesType.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterViewModelTests.kt
Labels: pr:fix
