Repository RevenueCat/purchases-android, pull requests merged in 2025-08, with the labels that each got.

#2579 Expose getStorefront APIs in CustomEntitlementComputation flavor
  api-tester/src/defaults/java/com/revenuecat/apitester/java/PurchasesAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/PurchasesAPI.kt
  api-tester/src/main/java/com/revenuecat/apitester/java/PurchasesCommonAPI.java
  api-tester/src/main/java/com/revenuecat/apitester/kotlin/PurchasesCommonAPI.kt
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/customEntitlementComputation/kotlin/com/revenuecat/purchases/Purchases.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/coroutinesExtensions.kt
  purchases/src/defaults/kotlin/com/revenuecat/purchases/listenerConversions.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/CoroutinesExtensionsCommon.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/ListenerConversionsCommon.kt
  ui/revenuecatui/api.txt
Labels: pr:other, pr:force_patch

#2586 Add warning on V9 CHANGELOG
  CHANGELOG.md
Labels: pr:other

#2584 Fix insets in Paywall Tester
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/PaywallTesterApp.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/AppScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/CustomerCenterScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/MainScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/appinfo/AppInfoScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/offerings/OfferingsScreen.kt
  examples/paywall-tester/src/main/java/com/revenuecat/paywallstester/ui/screens/main/paywalls/PaywallsScreen.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
Labels: pr:other

#2554 Support test store
  purchases/build.gradle.kts
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/EntitlementInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/OfferingParserFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/AppConfig.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/RestoreStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStoreBillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStoreOfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/teststore/TestStoreProductConverter.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/AlertDialogHelper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PreviewOfferingParser.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/BillingFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/OfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesCanMakePaymentsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesLifecycleTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/AmazonOfferingsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/amazon/BillingFactoryAmazonTest.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/AppConfigTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/BaseHTTPClientTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/diagnostics/DiagnosticsTrackerTest.kt
  purchases/src/test/java/com/revenuecat/purchases/teststore/TestStoreBillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/teststore/TestStoreOfferingParserTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/attributes/SubscriberAttributesPurchasesTests.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/PurchaseInformationCardView.kt
Labels: pr:other

#2590 Fail configure call if using test api key in release builds
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
Labels: pr:other

#2591 Rename TestStore to SimulatedStore
  purchases/build.gradle.kts
  purchases/src/main/kotlin/com/revenuecat/purchases/APIKeyValidator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/BillingFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/OfferingParserFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/models/TestStoreProduct.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/simulatedstore/SimulatedStoreBillingWrapper.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/simulatedstore/SimulatedStoreOfferingParser.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/simulatedstore/SimulatedStoreProductConverter.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/simulatedstore/SimulatedStorePurchasingData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/ConfigureStrings.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/RestoreStrings.kt
  purchases/src/test/java/com/revenuecat/purchases/APIKeyValidatorTest.kt
  purchases/src/test/java/com/revenuecat/purchases/BasePurchasesTest.kt
  purchases/src/test/java/com/revenuecat/purchases/PurchasesFactoryTest.kt
  purchases/src/test/java/com/revenuecat/purchases/simulatedstore/SimulatedStoreBillingWrapperTest.kt
  purchases/src/test/java/com/revenuecat/purchases/simulatedstore/SimulatedStoreOfferingParserTest.kt
  purchases/src/test/java/com/revenuecat/purchases/simulatedstore/SimulatedStoreProductConverterTest.kt
  purchases/src/testDefaults/kotlin/com/revenuecat/purchases/PurchasesTest.kt
Labels: pr:other

#2594 Add alias users backend call
  purchases/src/main/kotlin/com/revenuecat/purchases/common/Backend.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/Endpoint.kt
  purchases/src/test/java/com/revenuecat/purchases/common/backend/BackendTest.kt
  purchases/src/test/java/com/revenuecat/purchases/common/networking/EndpointTest.kt
Labels: pr:other

#2596 Show a subscribe button in customer center when there are no subscriptions
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/CustomerCenterConfigData.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/customercenter/ScreenOfferingExtensions.kt
  purchases/src/test/java/com/revenuecat/purchases/backend_integration_tests/ProductionBackendIntegrationTest.kt
  purchases/src/test/java/com/revenuecat/purchases/customercenter/ScreenOfferingExtensionsTest.kt
  purchases/src/test/java/com/revenuecat/purchases/customercenter/ScreenOfferingTest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/InternalCustomerCenter.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/ScreenOfferingExtensions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/actions/CustomerCenterAction.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/data/CustomerCenterState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/views/NoActiveUserManagementView.kt
Labels: pr:feat, feat:Customer Center

#2599 Add log when restoring purchases finds no purchases with some troubleshooting
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesOrchestrator.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/strings/RestoreStrings.kt
Labels: pr:other

#2607 Migrate deprecated kotlinOptions to compilerOptions
  api-tester/build.gradle.kts
  baselineprofile/build.gradle.kts
  dokka-hide-internal/build.gradle.kts
  examples/CustomEntitlementComputationSample/app/build.gradle.kts
  examples/MagicWeather/app/build.gradle.kts
  examples/MagicWeatherCompose/app/build.gradle.kts
  examples/paywall-tester/build.gradle.kts
  examples/web-purchase-redemption-sample/build.gradle.kts
  test-apps/testpurchasesandroidcompatibility/build.gradle.kts
  test-apps/testpurchasesuiandroidcompatibility/build.gradle.kts
  ui/revenuecatui/build.gradle.kts
Labels: pr:other

#2610 Add APIs for hybrid SDKs to set presentedOfferingContext
  api-tester/src/defaults/java/com/revenuecat/apitester/java/revenuecatui/PaywallViewAPI.java
  api-tester/src/defaults/kotlin/com/revenuecat/apitester/kotlin/revenuecatui/PaywallViewAPI.kt
  ui/revenuecatui/api.txt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallOptions.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivity.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityArgs.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/activity/PaywallActivityLauncher.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/OriginalTemplatePaywallFooterView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/views/PaywallView.kt
Labels: pr:other, pr:force_patch

#2604 Fixes price formatting discrepancies on Paywalls for `{{ product.price_per_[day|week|month|year] }}`
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/PreviewOfferingParser.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/ktx/Localization.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallState.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/VariableProcessorV2.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/helpers/OfferingToStateMapper.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/text/TextComponentViewVariablesTests.kt
  ui/revenuecatui/src/test/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/PaywallStateLoadedComponentsLocaleTests.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2608 Introduce runtime annotations library and add stability annotations for increasing UI performances
  gradle/libs.versions.toml
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/build.gradle.kts
  purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/CarouselComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/IconComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ImageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PackageComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PartialComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PurchaseButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StackComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/StickyFooterComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TabsComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TextComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/TimelineComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Badge.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Border.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ColorInfo.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/CornerRadiuses.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Dimension.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/ImageUrls.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/MaskShape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Padding.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shadow.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Shape.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/properties/Size.kt
  test-apps/testpurchasesandroidcompatibility/build.gradle.kts
  ui/revenuecatui/api.txt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/properties/BackgroundStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/RemoteImage.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/customercenter/viewmodel/CustomerCenterViewModel.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/data/processed/TemplateConfiguration.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/CustomFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/CustomParcelizableFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/GoogleFontProvider.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFont.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/fonts/PaywallFontFamily.kt
Labels: pr:RevenueCatUI, pr:other

#2621 Migrate RC SharedPreferences data to a separate file
  purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/SharedPreferencesManager.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/common/diagnostics/DiagnosticsSynchronizer.kt
  purchases/src/test/java/com/revenuecat/purchases/common/SharedPreferencesManagerTest.kt
Labels: pr:other

#2629 Fix integration tests shared preferences file
  purchases/src/androidTest/kotlin/com/revenuecat/purchases/BasePurchasesIntegrationTest.kt
Labels: pr:other

#2623 MON-1193 Support delayed close button (Component Transitions)
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/ButtonComponent.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallAnimation.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallTransition.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/EnumAsObjectSerializer.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PaywallTransitionTest.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/TransitionView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/button/ButtonComponentView.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/ButtonComponentStyle.kt
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/components/style/StyleFactory.kt
Labels: pr:feat

#2642 Fix PaywallDialog going over screen size on Android 35+
  ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/PaywallDialog.kt
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#2641 MON-1193 flatten Transition JSON structure after chatting more thoroughly with team
  purchases/api-defauts.txt
  purchases/api-entitlement.txt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallAnimation.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/paywalls/components/PaywallTransition.kt
  purchases/src/main/kotlin/com/revenuecat/purchases/utils/serializers/EnumAsObjectSerializer.kt
  purchases/src/test/java/com/revenuecat/purchases/paywalls/components/PaywallTransitionTest.kt
Labels: pr:other
